### ISSUE TITLE
Pass signalFxAccessToken to consul monitor automatically?

### ISSUE THREAD

**Issue by jalaziz** [signalfx/signalfx-agent#1001]
The `collectd/consul` plugin configuration can optionally accept `signalFxAccessToken` to send leadership change events.

Currently, the token has to be passed manually. Would it be possible to pass it in automatically from the top-level `signalFxAccessToken` config? This would simplify  configuration  and allow the default dashboard to completely work out=of-the-box without any surprises.

**Comment by keitwb** [comment]
It is _possible_, but we would rather avoid introducing more "pass down" in the config to make things simpler in the agent.  

There is a bigger problem with this monitor specifically in that the `collectd/consul` monitor should emit events back to the main agent process, which should then forward them to ingest using the main token configured.  Instead, that plugin tries to emit events directly to ingest, and in fact it will only work if your SignalFx org is in our original US0 realm ([event url is hardcoded](https://github.com/signalfx/collectd-consul/blob/master/consul_plugin.py#L927)).

In keeping with our pattern, we will probably rewrite this monitor in Go, which will eliminate the token config altogether.  Do you currently have any issues with the monitor other than the redundancy of the token config?  You can kind of mitigate the redundancy by using YAML anchors/references, or the [remote config](https://github.com/signalfx/signalfx-agent/blob/master/docs/remote-config.md) feature in the agent.

**Comment by jalaziz** [comment]
@keitwb makes sense. Actually, the US0 realm issue would affect us. I noticed that in the source, but thought events may be forwarded. We haven't had a leader change event, so I had not noticed it still wasn't working.

Emitting events back to the agent certainly makes sense.

We've had no other issues with the monitor so far, the only default graphs that are empty seems to be the leader state graphs.

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
