### ISSUE TITLE
Enable collectd/cpu metrics as default?

### ISSUE THREAD

**Issue by jalaziz** [signalfx/signalfx-agent#1007]
I was surprised to realize that none of the `collectd/cpu` metrics were enabled by default. Besides there appearing to be no other way to break apart CPU usage out of the box, it is expected by the built-in Cassandra dashboard (the "CPU %" chart breaks without it enabled).

It is also included in the default agent configuration: https://github.com/signalfx/signalfx-agent/blob/master/packaging/etc/agent.yaml

**Comment by keitwb** [comment]
Yes, that is essentially a bug given our criteria for which metrics get turned on by default or not.  Any metric used in built in content is supposed to be on by default.

We'll switch it so it gets categorized as a "host" metric so it won't count against your custom metric count, and also update the agent to make it default out of the box.  In the meantime, you can enable it like this:

```
- type: collectd/cpu
  extraMetrics:
    - cpu.idle
```

**Comment by jalaziz** [comment]
Thanks! Already have.

Any chance of having the rest of the `cpu` metrics enabled by default? I don't believe it's currently possible to tell if the host is spending all it's time in iowait, or in the hypervisor, or anywhere else. CPU utilization alone can be misleading. Those metrics can be immensely useful and it seems odd that they count against the custom metric count in general. In general, other products we've used collect them by default. Apologies if that's a bigger discussion.

**Comment by keitwb** [comment]
Yeah when we switched to the host-based pricing model the determining factor for what was host vs custom was whether it is in the built-in content that we had, and in all of that only `cpu.utilization` is used (and `cpu.idle` which should now be default as of 4.12.0, and should also be categorized as host).  I would recommend bringing it up with your account exec.
