### ISSUE TITLE
Python is not loading the correct certificate bundle in the docker image

### ISSUE THREAD

**Issue by jalaziz** [signalfx/signalfx-agent#1026]
I recently an into issues running the mongodb monitor with TLS enabled. After several hours of debugging, I finally isolated the issue to the certificate bundle included in the docker image.

If I download the latest bundle from https://mkcert.org/generate/ and set SSL_CERT_FILE, everything appears to work fine. Without the latest bundle, the pymongo throws the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python2.7/site-packages/pymongo/database.py", line 1018, in authenticate
    connect=True)
  File "/lib/python2.7/site-packages/pymongo/mongo_client.py", line 439, in _cache_credentials
    writable_preferred_server_selector)
  File "/lib/python2.7/site-packages/pymongo/topology.py", line 210, in select_server
    address))
  File "/lib/python2.7/site-packages/pymongo/topology.py", line 186, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
```

Unfortunately, the error doesn't appear in the SignalFx logs (presumably because collectd orr the agent times out before the error is thrown).

For the time being, I've fixed the issue by adding the following commands to a wrapping Dockerfile that extends from the published agent docker image:
```
RUN curl https://mkcert.org/generate/ -o /etc/ssl/certs/updated-ca-bundle.pem
ENV SSL_CERT_FILE=/etc/ssl/certs/updated-ca-bundle.pem
```

**Comment by keitwb** [comment]
Do you mind sharing the domain that the agent is trying to verify but can't? The docker image for the agent uses the system certs from Ubuntu 16.04 and we make sure to pull the latest base image every time we do a build, so I am surprised something is missing.

**Comment by jalaziz** [comment]
> Do you mind sharing the domain that the agent is trying to verify but can't? The docker image for the agent uses the system certs from Ubuntu 16.04 and we make sure to pull the latest base image every time we do a build, so I am surprised something is missing.

I'm hesitant to post the full hostname publicly, but it's of the form `*.mongodb.net`.  The certificate chain  can be found here: https://gist.github.com/jalaziz/3a9ec245c13cc479e9e75cc52592e959

I should add, it may not be the `/etc/ssl/certs/ca-certificates.crt` file that is the problem, but rather the SSL bundle used by python or pymongo (which should be `/etc/ssl/certs/ca-certificates.crt`, but may not be?).

**Comment by jalaziz** [comment]
Ok, so I did some more testing and setting `SSL_CERT_FILE` to `/etc/ssl/certs/ca-certificates.crt` fixes the problem as well. I had assumed the cert file was being set properly, but it appears that it wasn't.

The real issue appears to be that Python (or at least PyMongo) is not loading the cert bundle.

**Comment by keitwb** [comment]
Ok, that clarifies things a lot, thanks.  I made the linked PR to hopefully fix it.  If running outside of a Docker container it shouldn't be a problem.

We probably also need to update the pymongo version at some point to better support Mongo 4.x but that will require some more in-depth testing.

**Comment by jalaziz** [comment]
> Ok, that clarifies things a lot, thanks. I made the linked PR to hopefully fix it. If running outside of a Docker container it shouldn't be a problem.

Yeah. I need to look deeper into it, but I think it's probably something that is lost when going from Ubuntu to the scratch base image. Not quite sure if it's the `SSL_CERT_FILE` env var that is set normally or if there is something else that tells the libraries where to look. Will dig deeper tonight. In either case, your PR should fix it.

> We probably also need to update the pymongo version at some point to better support Mongo 4.x but that will require some more in-depth testing.

That would be great. Happy to help testing, but we're only running Mongo 3.4 currently. We should be upgrading to 3.6 soon. So while I can't promise testing on 4.x, I can at least promise that we will run the check with the updated driver for an extended period.

**Comment by jalaziz** [comment]
]Spent some more time trying to understand why this was broken in the first place and this is what I discovered.

First, by default, the Python ssl library is looking at `/usr/lib/ssl/cert.pem` and `/usr/lib/ssl/certs`.
```
>>> import ssl
>>> ssl.get_default_verify_paths()
DefaultVerifyPaths(cafile=None, capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/usr/lib/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/usr/lib/ssl/certs')
```

If we look at the ubuntu 16.04 container, and check the OpenSSL path, wee see:
```
openssl version -a
OpenSSL 1.0.2g  1 Mar 2016
...
OPENSSLDIR: "/usr/lib/ssl"
```

If we check `/usr/lib/ssl`, we see:
```
ls -al /usr/lib/ssl/
total 16
drwxr-xr-x 3 root root 4096 Oct 11 19:41 .
drwxr-xr-x 1 root root 4096 Oct 11 19:42 ..
lrwxrwxrwx 1 root root   14 Feb 27  2019 certs -> /etc/ssl/certs
drwxr-xr-x 2 root root 4096 Oct 11 19:41 misc
lrwxrwxrwx 1 root root   20 Feb 27  2019 openssl.cnf -> /etc/ssl/openssl.cnf
lrwxrwxrwx 1 root root   16 Feb 27  2019 private -> /etc/ssl/private
```

As it turns out, OpenSSL uses its own cert store by default. The directory is specified with [`--openssldir`](https://github.com/openssl/openssl/blob/master/INSTALL#L187) when building OpenSSL. Ubuntu and Debian systems will usually then symlink the OpenSSL cert directories to the system-level directories.

The `SSL_CERT_FILE` is actually used by OpenSSL libraries to override the default location, so the committed fix should hopefully help with anything else that relies on OpenSSL.

However, a lesser "band-aid" fix may be to copy over "/usr/lib/ssl/certs" and apply the same symlink.

**Comment by keitwb** [comment]
Thanks for looking into this more -- that is a very clear explanation. 

As long as the SSL_CERT_FILE is officially supported in OpenSSL, as it [appears to be](https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set_default_verify_paths.html), I'm fine with it.  As far as I know there is only the Go x509 implementation (which [looks in `/etc/ssl/certs` by default](https://golang.org/src/crypto/x509/root_linux.go)), Java (which bundles its own CA cert list in the JRE) and OpenSSL (collectd/Python) being used in the agent, so I think everything should be covered.
