### ISSUE TITLE
No possibility to pass extra Global Dimensions to Helm chart

### ISSUE THREAD

**Issue by ricardosilveiraolx** [signalfx/signalfx-agent#1040]
We would like to pass extra dimensions to configuration and it is not yet possible as the only extra dimension available is cluster name.

Will it be possible to have this available right on the next realease?

Thanks

**Comment by keitwb** [comment]
Hi @ricardosilveiraolx, this is a pretty simple addition so I went ahead and did it in #1042 (will be released soon).  If your config gets sufficiently complex or unorthodox, you can always use the `agentConfig` value to specify your own config and bypass all of the templating of the configmap.

**Comment by keitwb** [comment]
This is released in Helm chart 0.4.4.
