### ISSUE TITLE
python-monitor should log unhandled exceptions

### ISSUE THREAD

**Issue by xp-1000** [signalfx/signalfx-agent#1080]
Hello,

In my current environment (debian9), signalfx agent logging works fine through systemd.

Nevertheless, trying to create a new python-monitor script I noticed that if errors happen during script execution by the agent, this is not retrieved in agent logs.

For example, a python stacktrace due to unhandled exception will not be visible anywhere (in my knowledge) and so the script will fail silently.

This would be far better to provider logs from python script to signalfx agent logs

**Comment by jaysfx** [comment]
Thanks for the report. The fix has been merged to master.

**Comment by xp-1000** [comment]
awesome, thanks for this quick action.
I will test for the next released version.
