### ISSUE TITLE
Enable building custom monitors from extenal repos

### ISSUE THREAD

**Issue by captncraig** [signalfx/signalfx-agent#1115]
I have some custom integrations I would like to create as native signalfx agent monitors. I definitely prefer this to alternatives (python / collectd exec / prometheus) because it is fairly straightforward, and we already have a body of go collectors that can be fairly easily transformed into monitors.

The main problems are in logistics. Primarily the fact that all of the interfaces I need to create a monitor are in the `internal` packages. This means I can only build them **inside** of this repository. There are a number of reasons I (or others) might not want to do that:

- We have very specific integrations that will never be of interest to the community and will not be open-sourced.
- We would happily open source an integration, but would prefer to keep it separate from this repo. Possibly for governance or licensing or ownership reasons.
- We would like to be able to test and compile the integration in isolation from the rest of the agent code as much as possible.

Currently to make custom integrations I must build the agent myself. I agree this is probably unavoidable, and plugins are probably not worth the trouble for all the headache they give. I have another suggestion for making this part a little easier, but that will need to be another issue.

But right now my only option is to essentially:

1. Fork this repo
2. Add my own monitors in (adding files that are extremely unlikely to introduce future conflicts.
3. Add a new file somewhere sole to `import _` my package(s).
4. Compile the code.

I don't like this for a few reasons:

1. It is a bit of a pain to merge in upstream changes.
2. New developers on our end don't know the boundaries between our code and your code.

I would much rather have a dedicated monitors repo that has scripts to build the entire agent as appropriate. So my proposal is simply this:

I would like to move some packages from `github.com/signalfx/signalfx-agent/internal` into `github.com/signalfx/signalfx-agent/pkg`.

Specifically, I just need to move the packages that need to be directly imported to build a monitor. Going from the documentation, that includes:

- `github.com/signalfx/signalfx-agent/internal/core/config`
- `github.com/signalfx/signalfx-agent/internal/monitors`
- `github.com/signalfx/signalfx-agent/internal/monitors/types`
- `github.com/signalfx/signalfx-agent/internal/utils`

It is a fairly simple change, but it does touch a large number of files. Is there a significant reason not to make that change? I have tested this change, and have gotten things compiling after moving the packages. I will make a PR shortly.

**Comment by keitwb** [comment]
Would you write your own `main` method that proxies the agent's `main`, imports your new monitors, and then compile that?  I'm curious what the best workflow would be for what you are trying to do and if there is anything else the agent could do to facilitate it other than moving around packages.

**Comment by keitwb** [comment]
Actually looks like you can't import a main package in Go, so I'm curious what your workflow will be?

**Comment by captncraig** [comment]
So I "got it working" from a dedicated monitors repo. I checkout signalfx-agent as a submodule, and my build script does the following:

1. Copy my `imports.go` into `cmd/agent` alongside main.go.
2. Run some go module replacement voodoo on both sides to make sure they can find each other.
3. Run generate and build in the agent repo.

It works, but definitely feels a bit of a run-around. I would definitely rather do what you say and have my own main, but that would require the agent logic to be a fully importable module. In my mind this would look like:

- Move everything currently in `cmd/agent` into a diffrrent importable package (maybe `cmd/agent/agentmain`).
- `cmd/agent` becomes a one line call to `agentmain.Run()`. Then I can make my own main that does the same thing with different imports.
- Would probably need to check-in some of the generated go code so that `go get` is sufficient to build it. 

That's the solution that [caddy](https://github.com/caddyserver/caddy/blob/master/caddy/main.go) went with, and they have a similar style of "almost plugins but still need to be compiled in".

**Comment by keitwb** [comment]
@captncraig the changes have been merged to master.  Try it out and let us know if you encounter any other issues.

**Comment by captncraig** [comment]
Thank you! So far I am able to build successfully. Working on packaging and deployment and we'll see how it goes.
