### ISSUE TITLE
Helm: ability to add custom annotations to k8s pods

### ISSUE THREAD

**Issue by quangngotan95** [signalfx/signalfx-agent#1129]
As per [cluster-autoscaler docs](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node), we need to add `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"` annotation to the pods in order for a node to scale down.
However, it's unable to do so via the current helm charts.
Could we add support for that?

**Comment by jaysfx** [comment]
I haven't tested it but is the agent not ignored since it runs as a daemonset? From the docs:

> All pods running on the node (except these that run on all nodes by default, like manifest-run pods or pods created by daemonsets) can be moved to other nodes. 

What behavior have you observed?
