### ISSUE TITLE
Agent crashing on kubernetes cluster

### ISSUE THREAD

**Issue by coeyal** [signalfx/signalfx-agent#1151]
Agent keeps crashing on kubernetes.
I'm using EKS cluster 
`Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}`

Here is the Error from the logs:
`time="2020-01-19T21:47:49Z" level=info msg="Starting K8s API resource sync"
E0119 21:47:49.547438       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 2170 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x2260c00, 0x40b14c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x2260c00, 0x40b14c0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/signalfx/signalfx-agent/pkg/monitors/kubernetes/cluster/metrics.datapointsForJob(0xc00103e000, 0x2488e00, 0x2, 0x20ed403)
	/usr/src/signalfx-agent/pkg/monitors/kubernetes/cluster/metrics/jobs.go:25 +0x1ff
github.com/signalfx/signalfx-agent/pkg/monitors/kubernetes/cluster/metrics.(*DatapointCache).HandleAdd(0xc000cb3800, 0x2b75220, 0xc00103e000, 0x2b75220, 0xc00103e000)
	/usr/src/signalfx-agent/pkg/monitors/kubernetes/cluster/metrics/cache.go:109 +0x78d
github.com/signalfx/signalfx-agent/pkg/monitors/kubernetes/cluster.(*State).beginSyncForType.func3(0xc000f98480, 0x17, 0x17, 0xc000ddd808, 0x8, 0x0, 0x0)
	/usr/src/signalfx-agent/pkg/monitors/kubernetes/cluster/clusterstate.go:154 +0x2d4
k8s.io/client-go/tools/cache.(*FakeCustomStore).Replace(0xc0012482d0, 0xc000f98480, 0x17, 0x17, 0xc000ddd808, 0x8, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/fake_custom_store.go:91 +0x65
k8s.io/client-go/tools/cache.(*Reflector).syncWith(0xc00021e840, 0xc000f98300, 0x17, 0x17, 0xc000ddd808, 0x8, 0x0, 0xc000d74cc0)
	/go/pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:354 +0xf8
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc00021e840, 0xc0008f4400, 0xc000d74000, 0xc001181bb8, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:250 +0x8fa
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc00021e840, 0xc000d74000, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:257 +0x1a9
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:155 +0x33
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000b63778)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001181f78, 0x3b9aca00, 0x0, 0xc000c29901, 0xc000d74000)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc00021e840, 0xc000d74000)
	/go/pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:154 +0x16b
created by github.com/signalfx/signalfx-agent/pkg/monitors/kubernetes/cluster.(*State).beginSyncForType
	/usr/src/signalfx-agent/pkg/monitors/kubernetes/cluster/clusterstate.go:167 +0x2f6
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19a587f]`

By looking on the stack trace and the code it seems that when getting kubernetes jobs there is a call to null pointer. 
			datapoint.NewIntValue(int64(*job.Spec.Completions))

Here is the job description from kubernetes:
`➜  ~ kubectl describe job automation-d9c368
Name:           automation-d9c368
Namespace:      automation-testing
Selector:       controller-uid=88b3bc31-3ac4-11ea-b7bc-0203bc266fa1
Labels:         controller-uid=88b3bc31-3ac4-11ea-b7bc-0203bc266fa1
                job-name=automation-d9c368
Annotations:    <none>
Parallelism:    1
Completions:    <unset>
Start Time:     Sun, 19 Jan 2020 16:03:56 +0200
Completed At:   Sun, 19 Jan 2020 16:28:41 +0200
Duration:       24m
`

You can see that Completions attribute is unset. 

From kubernetes docs the value of job completion can be unset in some cases. 

> For a non-parallel Job, you can leave both .spec.completions and .spec.parallelism unset. When both are unset, both are defaulted to 1. 

> For a fixed completion count Job, you should set .spec.completions to the number of completions needed. You can set .spec.parallelism, or leave it unset and it will default to 1.

> For a work queue Job, you must leave .spec.completions unset, and set .spec.parallelism to a non-negative integer
[https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/](url)

 So unset completion attribute should be handled.

**Comment by keitwb** [comment]
Thanks for reporting this @coeyal.  We'll take a look at it today and push out a patch release as soon as possible to fix this.

**Comment by keitwb** [comment]
This was patched and released in https://github.com/signalfx/signalfx-agent/releases/tag/v4.18.2
