### ISSUE TITLE
Make collectd/statsd metrics prefix optional

### ISSUE THREAD

**Issue by yzabalotski** [signalfx/signalfx-agent#1196]
Hi,

Could you clarify why is type prefix is needed for metrics from [collecd/statsd](https://github.com/signalfx/signalfx-agent/blob/master/docs/monitors/collectd-statsd.md)?

It will be nice to have it configurable (enable/disable), because it's hard to migrate between different statsd monitors (e.g. statsd).

Thanks

**Comment by jaysfx** [comment]
@yzabalotski unfortunately prefixing the type name is generic behavior in the collectd listener that's not configurable per-monitor. However in your chart you can account for this. If the metric name before was `gauge.memory.used` and now it is `memory.used` you could use the metric `*memory.used` to match either metric. Would this work around the issue?

**Comment by yzabalotski** [comment]
@jaysfx 
Yeah, it works for charts, but it breaks integration with other services, e.g. grafana. As I got, there're no chances to get such option?

**Comment by jaysfx** [comment]
We try to focus our efforts on improving new Go-based monitors as much as we can. If the statsd monitor isn't sufficient have you tried https://docs.signalfx.com/en/latest/integrations/agent/monitors/telegraf-statsd.html?

**Comment by yzabalotski** [comment]
Yes, looks like it parses all metrics correctly, but doesn't send them into signalfx.

Configuration:
```
monitors:
 - type: telegraf/statsd
   parseDataDogTags: true
```

Just replaced collectd/statsd to telegraf/statsd. Looks like messages are queued, but are not sent.

Any ideas?

**Comment by jaysfx** [comment]
Hard to say without digging in more to the config/account. Can you contact support through the app? They'll be better able to assist there.

**Comment by yzabalotski** [comment]
Thanks
