### ISSUE TITLE
High CPU Usage (Part 2)

### ISSUE THREAD

**Issue by jwcmd** [signalfx/signalfx-agent#1203]
Good Afternoon! 

This is a continuation of an issue that we thought was resolved but which has now resurfaced. 

https://github.com/signalfx/signalfx-agent/issues/1072

We're seeing high CPU usage by SignalFX Agent on a subset of our servers.

`ii  signalfx-agent                   4.19.2-1                                   amd64        The SignalFx metric agent`

```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
```

I've submitted the data collected from the requested profiling data and I've submitted it via Slack. Please let me know if there's any additional data I can provide.

**Comment by jwcmd** [comment]
I should add that we've isolated a node that is actively in this state so that we can poke and prod at it if needed.

**Comment by dloucasfx** [comment]
@jwcmd 
Thanks for reporting this issue!

Few questions:

> I've submitted the data collected from the requested profiling data and I've submitted it via Slack. Please let me know if there's any additional data I can provide.
- Which slack and who did you send the data to?
- Did you open a support case for this issue? If not, can you please do. This helps us get the solution out faster and prevent information falling through the cracks.

**Comment by jwcmd** [comment]
Details were posted to the "cmd_poc" channel in the SignalFx External Slack org.

Ive just now opened a SFX Support case, Case 00011610.

Thanks @dloucasfx !

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
