### ISSUE TITLE
v5 introduces a breaking change on load metrics

### ISSUE THREAD

**Issue by xp-1000** [signalfx/signalfx-agent#1236]
Hello,

According to the documentation, the behavior of `load` monitor is different than the `collectd/load` one:

- For the new load monitor : 
https://docs.signalfx.com/en/latest/integrations/agent/monitors/load.html
>  Average CPU load of the system over the last 5 minutes. If the perCPU config option is true, this will be the average load per CPU.

But the default value is `false`:
> perCPU | no | bool | (default: false)

- For the old one (collectd) : 
https://docs.signalfx.com/en/latest/integrations/agent/monitors/collectd-load.html
>  Average CPU load per core over the last five minutes
This time by default the load is normalized per cpu/core

This difference between both beaviors is not without impact and I think this could lead to undesired alerts while the threshold on hypothetic detectors does not make sens anymore.

In my opinion, the best should be to make `perCPU` true by default because this is what everybody should want in general but if you do not want that I think there is should be, at least, a special note about this in the changelog:
https://github.com/signalfx/signalfx-agent/releases/tag/v5.0.0

**Comment by keitwb** [comment]
Hi @xp-1000, the `collectd/load` metric docs are actually wrong on this matter.  They in fact do _not_ average by CPU.  In fact, we originally implemented the new `load` monitor and had CPU averaging on by default, but later disabled it before the 5.0.0 release when we realized the incompatibility (see https://github.com/signalfx/signalfx-agent/pull/1171).  The `collectd/load` docs should have been fixed at that time, but weren't for some reason.  I tested the default configs of both monitors on a multi-core machine and the metrics are indeed identical.

We left `perCPU` defaulting to false for the very reason of making it fully compatible with the `collectd/load` monitor under a default configuration.  Setting `perCPU: true` is probably more useful for alerting, I agree, but cannot really be changed without introducing a major incompatibility now.

I made a new PR (#1237) to fix the incorrect collectd/load metric docs and hopefully prevent confusion in the future.

**Comment by xp-1000** [comment]
oh ok it makes sens ! thanks for quick and relevant answer.

To be honest I would prefer to see the perCPU set to true as default but now I understood collectd doc was incorrect this was the good choice to avoid any breaking change.

Not a big deal, I will set this parameter everywhere and I think we can close this issue now.

Thanks
