### ISSUE TITLE
new Datapointstoexclude

### ISSUE THREAD

**Issue by EvilAcid** [signalfx/signalfx-agent#1239]
https://github.com/signalfx/signalfx-agent/blob/c816e1ee7cc8c272e96c27124b4c8d9b44c09493/deployments/k8s/configmap.yaml#L80

doesn't the global MetricsToEnclude have to be rewritten to DatapointsToExclude for the update to version >5.0.0?

This did not work in my attempt. How do you see that?

**Comment by keitwb** [comment]
The _monitor-level_ `metricsToExclude` config was removed in 5.0.0 but the _top-level_ one that you linked to in the configmap was _not_ removed because there is no alternative at the top-level of the config to do filtering.  Are you getting an error when trying to deploy the Helm chart?
