### ISSUE TITLE
help about writing own monitor

### ISSUE THREAD

**Issue by xp-1000** [signalfx/signalfx-agent#1277]
Hello,

I seen the page https://github.com/signalfx/signalfx-agent/blob/master/docs/writing-a-monitor.md
which is exactly what I need to implement a new go based check into the agent.

Nevertheless, in my opinion it miss some useful information especially about: 

-  the process of integration. Indeed doc says

> Therefore right now, new monitors must be compiled into the agent binary.

So how can I enjoy my new monitor once implemented ? I don't see any doc to help how to build the agent from source.

- the availability in the upstream agent. could we expect to see our monitor merged upstream to share with others if generic and useful enough ? and how ?

- dev environment setup. I assume any PR on this repo will trigger a CI pipeline which could help us to test our monitor using the `*_test.go` files but it could be useful to provide some tricks in code to allow real testing outside the entire agent. (or help to build agent, see my first question)

A quick step by step getting started would be useful and allow easy contributions to improve the agent adding more capabilities.

For example, with my go 1.14.1 version : 

```
$ go get github.com/signalfx/signalfx-agent/pkg/core/config
# github.com/signalfx/signalfx-agent/pkg/core/config/sources/vault/auth
../github.com/signalfx/signalfx-agent/pkg/core/config/sources/vault/auth/gcp.go:73:2: cannot use *"github.com/hashicorp/vault-plugin-auth-gcp/vendor/github.com/hashicorp/vault/api".Secret value as type *"github.com/hashicorp/vault/api".Secret in return argument
../github.com/signalfx/signalfx-agent/pkg/core/config/sources/vault/auth/gcp.go:73:15: cannot use client (type *"github.com/hashicorp/vault/api".Client) as type *"github.com/hashicorp/vault-plugin-auth-gcp/vendor/github.com/hashicorp/vault/api".Client in argument to h.Auth
../github.com/signalfx/signalfx-agent/pkg/core/config/sources/vault/auth/iam.go:59:2: cannot use *"github.com/hashicorp/vault/vendor/github.com/hashicorp/vault/api".Secret value as type *"github.com/hashicorp/vault/api".Secret in return argument
../github.com/signalfx/signalfx-agent/pkg/core/config/sources/vault/auth/iam.go:59:15: cannot use client (type *"github.com/hashicorp/vault/api".Client) as type *"github.com/hashicorp/vault/vendor/github.com/hashicorp/vault/api".Client in argument to h.Auth
```

problably a problem from my side but this is why I think more help could be relevant.

thanks

**Comment by mstumpfx** [comment]
Hi @xp-1000 
> So how can I enjoy my new monitor once implemented ? I don't see any doc to help how to build the agent from source.
We have a developers guide you can check out regarding building the agent here: https://github.com/signalfx/signalfx-agent/blob/master/docs/development.md

> dev environment setup. I assume any PR on this repo will trigger a CI pipeline which could help us to test our monitor using the *_test.go files but it could be useful to provide some tricks in code to allow real testing outside the entire agent. (or help to build agent, see my first question)
Yep, our full CI pipeline should run against PRs, however if you want to run tests locally build the agent locally and run `make tests`. I would recommend doing this in the dev image (the developer guide talks about this a little).

I hope this helps, thanks.

**Comment by xp-1000** [comment]
Hello, 
Yes thanks it help I will give a try and submit a PR based on this we will see
