### ISSUE TITLE
Simplify kubelet API configuration for authenticated endpoint

### ISSUE THREAD

**Issue by jalaziz** [signalfx/signalfx-agent#1278]
On EKS, the read-only unauthenticated kubelet API endpoint is disabled by default (see amazon-eks-ami#128).

While it is possible to override the `kubeletAPI` config option in the `agent.yaml` file, it's not the most convenient as you have to provide the full URL instead of just the port. Furthermore, because you have to provide the full URL, it's not possible to use the node hostname in the config (unless I'm missing something?).

To keep things consistent with other monitors, it may be more desirable to offer users the option to simply override the port and/or scheme.

Another option may be a simple "authenticated" flag that uses the authenticated 10250 port automatically.

Part of the reason why I'm bringing this up is that the k8s helm documentation does not mention the potential port issue (https://docs.signalfx.com/en/latest/integrations/kubernetes/k8s-quick-install.html) but the advanced install guide does (https://docs.signalfx.com/en/latest/integrations/kubernetes/k8s-advanced-installation.html#k8s-advanced-install). While it's possible to pass the `kubeletAPI.url` value to the helm chart, it would be great if the necessary changes were more visible/simpler.

**Comment by mstumpfx** [comment]
hi @jalaziz 
> While it is possible to override the kubeletAPI config option in the agent.yaml file, it's not the most convenient as you have to provide the full URL instead of just the port. Furthermore, because you have to provide the full URL, it's not possible to use the node hostname in the config (unless I'm missing something?).

You should be able to use the node name in the config like:
`- type: kubelet-stats
  kubeletAPI:
    url: https://${MY_NODE_NAME}:10250`

This `MY_NODE_NAME` is an env variable that gets set by the daemonset here: https://github.com/signalfx/signalfx-agent/blob/master/deployments/k8s/daemonset.yaml#L76 or if installed via helm, here: https://github.com/signalfx/signalfx-agent/blob/master/deployments/k8s/helm/signalfx-agent/templates/daemonset.yaml#L95

I think we could add a section to the k8s install guide that mentions these environment variables that are exposed for users to use, so we'll keep this in mind.

>To keep things consistent with other monitors, it may be more desirable to offer users the option to simply override the port and/or scheme.

Another good suggestion, we'll take this into consideration.
Thanks!

**Comment by jalaziz** [comment]
> This `MY_NODE_NAME` is an env variable that gets set by the daemonset here: https://github.com/signalfx/signalfx-agent/blob/master/deployments/k8s/daemonset.yaml#L76 or if installed via helm, here: https://github.com/signalfx/signalfx-agent/blob/master/deployments/k8s/helm/signalfx-agent/templates/daemonset.yaml#L95

Ah, did not notice that! That certainly helps. Thanks!
