### ISSUE TITLE
Ansible : Yaml config

### ISSUE THREAD

**Issue by Poil** [signalfx/signalfx-agent#1292]
Hi,

I don't understand the interest of taking a yaml configuration to upload it as yaml configuration, if I try to configure something like 

```
sfx_agent_config:
  signalFxAccessToken: "{{ signalFxAccessToken }}"
  signalFxRealm: eu0
  monitors:
    - type: cpu
    - type: filesystems
    - type: disk-io
    - type: net-io
    - type: load
    - type: memory
    - type: vmem
    - type: host-metadata
    - type: processlist
    - type: collectd/custom
      template: |
        LoadPLugin curl_json
        <Plugin curl_json>
          <URL "https://myurl.com">
            <Key "time">
              Type "http_response_time"
            </Key>
          </URL>
        </Plugin>
``` 

On server side it generates

```
-   template: "LoadPLugin curl_json\n<Plugin curl_json>\n  <URL \"https://myurl.com\"\
        >\n    <Key \"sql/duration\">\n      Type \"http_response_time\"\n    </Key>\n\
        \    <Key \"redis/duration\">\n      Type \"response_time\"\n    </Key>\n\
        \    <Key \"AzureSearch/duration\">\n      Type \"response_time\"\n    </Key>\n\
        \    <Key \"filesystem\">\n      Type \"response_time\"\n    </Key>\n  </URL>\n\
        </Plugin>\n"
    type: collectd/custom
```

I also tried  to encapsulate in `!unsafe` and `{% raw %}` but it produces invalid configuration

Best regards,

**Comment by keitwb** [comment]
That appears correct to me.  Ansible is not preserving the same style of string and is just dumping it in a giant `"` string literal on one line, but that should be fine.  Kind of ugly but I'm not sure there is much that can be done unless Ansible has a setting to tweak it, which I am not aware of.

**Comment by keitwb** [comment]
Please reopen if I have misunderstood your issue, but otherwise I don't think there is anything we can do on our end.
