### ISSUE TITLE
Allow to split configuration

### ISSUE THREAD

**Issue by Poil** [signalfx/signalfx-agent#1294]
Hi,

A monolithic configuration is a pain for automation, please allow inclusion via a glob pattern or something like that.

Best regards,

**Comment by mstumpfx** [comment]
Hi @Poil - can you take a look at our documentation on configuration here https://docs.signalfx.com/en/latest/integrations/agent/remote-config.html
We have some support for globbed paths, and some other ways of remote configuration. 

Let me know if this isn't what you meant - Thanks

**Comment by Poil** [comment]
It's exactly what I want, thanks
