### ISSUE TITLE
Embedded libraries CVE

### ISSUE THREAD

**Issue by Poil** [signalfx/signalfx-agent#1295]
Hi,

It looks like the embedded libraries are old and vulnerable.
I just look 3 and these 3 have vulnerabilities `libssl 1.0.0 / libpq 5.8 / libpcap 1.7.4`
You also embed binaries like bash, ss ... that can have high vulnerability risk.

What is your politic to maintain these dependencies ?

Best regards,

**Comment by jchengsfx** [comment]
@Poil Thank you for the input.  The SignalFx agent is currently based on Ubuntu 16.04, and we pull the latest available updates with each release.  Unfortunately, upgrading to a newer version of Ubuntu will break backward compatibility on distros with older kernels for some of our customers.

**Comment by Poil** [comment]
OK, this look likes good. Thansk
