### ISSUE TITLE
Add native monitor for webcheck

### ISSUE THREAD

**Issue by xp-1000** [signalfx/signalfx-agent#1301]
Hello,

a simple webcheck to retrieve http and ssl metrics will be a good feature even if signalfx does not aim to provide synthetics features this could help to check internal or simple web services out the box.

- https://docs.signalfx.com/en/latest/integrations/agent/monitors/collectd-health-checker.html
- https://collectd.org/wiki/index.php/Plugin:cURL
Both are able to achieve webcheck but it miss some feature and metrics in my opinion.

**Comment by keitwb** [comment]
Fixed by #1302
