### ISSUE TITLE
Quay.io down, is there a mirror for docker images?

### ISSUE THREAD

**Issue by pdecat** [signalfx/signalfx-agent#1326]
Quay.io is down right now, is there a mirror for docker images?

```
# docker pull quay.io/signalfx/signalfx-agent:5.1.6
Error response from daemon: Get https://quay.io/v2/signalfx/signalfx-agent/manifests/5.1.6: Get https://quay.io/v2/auth?scope=repository%3Asignalfx%2Fsignalfx-agent%3Apull&service=quay.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

> Quay.io outage
> We are currently investigating this issue.
> Posted 2 hours ago. May 19, 2020 - 03:30 EDT

see https://status.quay.io/incidents/kw2627bsdwd9

**Comment by keitwb** [comment]
No sorry we don't have any alternate Docker registries at this time.  The best option at this point is to just build the agent image from source with `AGENT_IMAGE_NAME=<my image name> AGENT_VERSION=<my version> make image` and push it to your own registry.  We will look into using the Artifactory server that we put our APT and RPM packages on as a backup registry (@jchengsfx).

**Comment by keitwb** [comment]
Well that was a long outage but they seem to be back up.
