### ISSUE TITLE
No way to set SKIP_KUBERNETES_NODE_UID_DIM via helm chart

### ISSUE THREAD

**Issue by mrroach** [signalfx/signalfx-agent#1331]
When attempting to run the agent without any service account, there is not a way to prevent `hostid.KubernetesNodeUID` from causing the process to die. Adding a way to set the above env var, or remove the MY_NODE_NAME env var (or something else?) would be very helpful.

**Comment by mrroach** [comment]
I'll add that this bit of code could just have the first line moved within the `if` block to simplify this as well.
```
	hostDims := hostid.Dimensions(conf)
	if !conf.DisableHostDimensions {
		log.Infof("Using host id dimensions %v", hostDims)
		conf.Writer.HostIDDims = hostDims
	}
```

**Comment by keitwb** [comment]
Thanks @mrroach.  You are right, the derivation of host dims should really be in the conditional.  I did that and also added the ability to add arbitrary envvars to the pod spec via the Helm chart.  Hope this helps.

**Comment by mrroach** [comment]
awesome! that was fast, thanks!

**Comment by mrroach** [comment]
does the chart version need to be incremented for these changes to become available?

**Comment by keitwb** [comment]
Yes, we'll need to do another Helm chart release which will go out with the next agent release.  The master version of the chart right now won't work with the latest released agent since I added a config option to the Helm chart that hasn't been released yet.
