### ISSUE TITLE
Run agent in Openshift without node permissions

### ISSUE THREAD

**Issue by trotman23** [signalfx/signalfx-agent#1345]
Is it possible to run the agent in openshift without the cluster role binding that grants access to [get/list/watch](https://github.com/signalfx/signalfx-agent/blob/master/deployments/k8s/clusterrole.yaml#L28-L30) [nodes](https://github.com/signalfx/signalfx-agent/blob/master/deployments/k8s/clusterrole.yaml#L16)?

Some background: I'm trying to run the agent in a multi-tenant openshift cluster where I cannot access any resources outside of a single namespace, and can not access cluster-level resources (like nodes). 

I realize that without some of these cluster-level permissions, the agent will be limited in what it can actually monitor, but was hoping it could at least monitor pods in my namespace. 

When I run the agent in openshift, I get the following error on start up: 
```
time="2020-06-03T00:15:23Z" level=info msg="Starting up agent version 5.2.1"
--
  | time="2020-06-03T00:15:23Z" level=info msg="Watching for config file changes"
  | time="2020-06-03T00:15:23Z" level=info msg="New config loaded"
  | time="2020-06-03T00:15:23Z" level=info msg="Using log level debug"
  | time="2020-06-03T00:15:23Z" level=info msg="Fetching host id dimensions"
  | time="2020-06-03T00:15:23Z" level=info msg="Trying to get fully qualified hostname"
  | time="2020-06-03T00:15:23Z" level=info msg="Using hostname signalfx-agent-64659d9b56-jgbp4"
  | time="2020-06-03T00:15:23Z" level=error msg="Could not fetch node with name <REDACTED> from K8s API: nodes \"<REDACTED>\" is forbidden: User \"system:serviceaccount:my-namespace:signalfx-agent\" cannot get nodes at the cluster scope: no RBAC policy matched"
```

My service account has the basic `read` role for the namespace in question (which without listing all the permissions out, is basically scoped to reading all resources in the namespace). 

I've tried playing around with the `k8s-api` observer configurations and set `discoverNodes` to `false`, but the agent still tries to read the node resource from the api server upon initialization. 
I even disabled all observers and monitors I was trying out, and observed the same behavior. 

Is what i'm trying to do possible?

**Comment by dloucasfx** [comment]
@trotman23 this is an unsupported configuration however, you can skip the code that is triggering the error 
```
