### ISSUE TITLE
SIGSEGV in statsd monitor

### ISSUE THREAD

**Issue by pdecat** [signalfx/signalfx-agent#1367]
Faced this error for the first time today with the quay.io/signalfx/signalfx-agent:5.3.2 docker image running on GKE:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc30 pc=0x468c45]

goroutine 242 [running]:
github.com/signalfx/signalfx-agent/pkg/monitors/statsd.(*statsDListener).Read(0xc0005018f0)
	/usr/src/signalfx-agent/pkg/monitors/statsd/statsd.go:78 +0x256
```

Not sure yet what could cause this yet as the corresponding code seems relatively trivial: https://github.com/signalfx/signalfx-agent/blob/v5.3.2/pkg/monitors/statsd/statsd.go#L78

**Comment by keitwb** [comment]
Thanks for bringing this to our attention @pdecat .  I think the problem lies in how the metricBuffer variable is used across goroutines without locking.  The linked PR should fix that.

**Comment by pdecat** [comment]
Good point, did not realize Read() and FetchMetrics() could be invoked concurrently:
- https://github.com/signalfx/signalfx-agent/blob/v5.3.2/pkg/monitors/statsd/monitor.go#L112
- https://github.com/signalfx/signalfx-agent/blob/v5.3.2/pkg/monitors/statsd/monitor.go#L115

**Comment by keitwb** [comment]
Ok @pdecat, it is merged and we'll release it soon.
