### ISSUE TITLE
Missconfig in the agent config span billions of log lines in syslog

### ISSUE THREAD

**Issue by simon-jt** [signalfx/signalfx-agent#1380]
Hi,

I used the ansible role to install the agent. A miss config just raised around 7 billions of error lines in the syslog in a couple of minutes (a couple of Gigabytes).

It might be safer to not send a log line for each time event in case of an error in the config file of the agent.

OS: ubuntu:16.04
Agent-version:latest

**Comment by keitwb** [comment]
Hi @simon-jt, can you give a sample of the error logs?  I'm not aware of anything in the agent that would log that quickly.

**Comment by simon-jt** [comment]
Hello @keitwb here is a bit of logs

```

Jul  6 16:16:24 ip-172-18-3-23 signalfx-agent[11551]: time="2020-07-06T16:16:24Z" level=error msg="Unable to update dimension, retrying" correlation="&{ AWSUniqueId i-xxxxxxxxxxxxxx_eu-west-1_051870916264 }" error="error making HTTP request to https://api.us0.signalfx.com/v2/apm/correlate/AWSUniqueId/i-xxxxxxxx_eu-west-1_xxxxxxxxxxx: Get \"https://api.us0.signalfx.com/v2/apm/correlate/AWSUniqueId/i-xxxxxxxxxx_eu-west-1_xxxxxxxxxxx\": net/http: invalid header field value \"$ANSIBLE_VAULT;1.1;AES256\\n61613639333762633765353361346637396137386433383162373834393830646231623762613066\\n346633663563393962373535373734313539616636370a653837336264636561336663323063\\n3939333939653463386163656565383864616239623066361393564663438366564316632\\n3061626161316635330a336265396564366334346636663734393731303338666461323835343334\\n33333936636237653366662616236613133386461386165316638653534666463386261303162\\n6433626334383734626638663463643639636330393737313338\\n\" for key X-Sf-Token" method=GET url="https://api.us0.signalfx.com/v2/apm/correlate/AWSUniqueId/i-xxxxxxxxxxx_eu-west-1_xxxxxxxxxxxxxx"
```
The crypted string is due to an ansible missconfig.

**Comment by keitwb** [comment]
@codesmith14 can you investigate this and make sure retries are being properly delayed with the APM correlation logic and not retrying too quickly?

**Comment by simon-jt** [comment]
Hi I was able to reproduce the issue on an EC2 instance using ubuntu 18.04 but not using Vagrant or Docker.

**Comment by codesmith14** [comment]
Thank you for your feedback. I am actively working on a fix for this as well as a fix for another issue that I've identified around the same area. I will update here once the changes are complete.

**Comment by keitwb** [comment]
@codesmith14 has implemented a fix for this and it should no longer be an issue in release 5.4.1+.  @simon-jt feel free to reopen if you encounter the issue again.  Hopefully this fixes it for you.

**Comment by simon-jt** [comment]
Hi @codesmith14 would it be possible to see the commit(s) that fixes the issue ?
