### ISSUE TITLE
Have explicit user Agent for HTTP checks

### ISSUE THREAD

**Issue by BzSpi** [signalfx/signalfx-agent#1455]
When the agent performs HTTP checks, the user agent used currently used is `Go-http-client/1.1`.

Is it possible to change it to something like `SignalFx SmartAgent/<agent-version>` ?

**Comment by BzSpi** [comment]
Also, if the default value could be overridden from the configuration, this would be fine.

**Comment by keitwb** [comment]
The related PR was merged and should be doable now.
