### ISSUE TITLE
telegraph sql monitor

### ISSUE THREAD

**Issue by bsunders** [signalfx/signalfx-agent#1461]
For host - please clarify this is the OS defined host and not the SQL name defined in SQL Server.
For the user, the script creates a u user ID called : signalfxagent but then the example uses SA password. This is also confusing as folk dont know if to use signalfxagent or sa.

**Comment by keitwb** [comment]
@bsunders can you make a patch in https://github.com/signalfx/signalfx-agent/blob/master/pkg/monitors/telegraf/monitors/mssqlserver/metadata.yaml and submit a PR?  I'm not entirely sure what you mean.

**Comment by aishvaryaps** [comment]
Is this supported on linux and windows agent both?

**Comment by keitwb** [comment]
@aishvaryaps This one is supported on both Windows and Linux.

**Comment by xp-1000** [comment]
> @aishvaryaps This one is supported on Windows because it is for MSSQL server.

also it is specified in the underlying telegraf official doc (which is already linked in signalfx doc) : https://github.com/influxdata/telegraf/tree/master/plugins/inputs/sqlserver

> It currently works with SQL Server 2008 SP3 and newer. Recorded metrics are lightweight and use Dynamic Management Views supplied by SQL Server.

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
