### ISSUE TITLE
Duplicate Metrics Reported across the board with the DaemonSet

### ISSUE THREAD

**Issue by RoopGuron** [signalfx/signalfx-agent#1490]
Since the K8s agent runs as a **DaemonSet** this results in metrics being scraped multiple times for each interval and be reported as a high count. 
No, doubt the DaemonSet is needed for metrics around worker and maser nodes, but a large chunk of metrics are needed to be scraped for a one-off endpoint. e.g.,, **kubernetes-apiserver** , **prometheus_exporter**

For instance,
    in a K8s EKS Cluster with 10 worker nodes, If one needs to scrape Control plane metrics via the endpoint: <eks-apiserver-url>/metrics using the _monitor: kubernetes-apiserver_ this results in all 10 _daemonSet signalfx-agent_  pods scraping this endpoint and reporting the metrics to the signalFx tenant.  
This impacts the _custom metrics count_ and hence the billing of the **SignalFX**  for the team. The count is amplified 10 times what it is supposed to be.
This is true for any _prometheus_exporter_ monitor type as well.
**BottomLine**
There is **_no configuration_** option for the above mentioned monitor types: _**kubernetes_apiserver**_ and **_prometheus_exporter_** to have the metrics be sent/reported only by the **_elected leader signalfx-agent pod._**

**Comment by dloucasfx** [comment]
@RoopGuron 
as a workaround, you can use discovery rules with the downward api env variable `MY_NODE_NAME` to pin monitors to a specific node.
for example, if the node name you want to use to run specific monitors is named `minikube` , just append this to your discovery rule 

```
&& "${MY_NODE_NAME}" == "minikube"
```

**Comment by RoopGuron** [comment]
@dloucasfx thanks for the quick response
I don't think that would work for our use cases 
and besides **discoveryRule** is to facilitate service discovery of sorts, identifying endpoints to be scraped. But the endpoints are static, identified and not associated with a pod/node
` - type: prometheus-exporter
      host: {{ .Values.ingressExternalSvc }}
      port: 9913
      metricPath: /metrics`
how would I pin down this particular monitor to be only running on one particular pod?

or another example,
```
 - type: kubernetes-apiserver
      useHTTPS: true
      useServiceAccount: true
      host: {{ .Values.eksApiServerUrl }}
      port: 443
      skipVerify: true
```
how would **discoveryRule**  ensure only one signalfx-agent pod is scraping the metrics?

**Comment by keitwb** [comment]
@RoopGuron In the case of something running on a non-schedulable node, or a completely third party service, you need to have a separate Smart Agent configuration and run the Smart Agent with a Deployment with `replicas: 1`.  This will get what you want and it ultimately the simplest solution.  We considered adding such functionality to the agent directly but it was deemed excessively complex given the relatively easy workaround with Deployments.  You should be able to reuse the secrets, roles, etc. between the DaemonSet and Deployment.

**Comment by RoopGuron** [comment]
@keitwb thanks for the pointer.
This thought did cross our mind, but wanted to check if there was some configuration switch built in that we were not able to decipher.
