### ISSUE TITLE
Health Check Endpoint

### ISSUE THREAD

**Issue by phr3nzii** [signalfx/signalfx-agent#1494]
It would be useful to have a health check endpoint so that we can configure pod liveness checks in Kubernetes. This would ensure that the agent is operating as expected.

**Comment by keitwb** [comment]
There kind of is with the status endpoint already.  By default it listens on `localhost:8095` as an HTTP server and should return a 200 response when the path `/` is hit.  Is that sufficient for a liveness check for you?

**Comment by phr3nzii** [comment]
@keitwb Yes, that will be ideal, thanks!

Do you think it would be a good idea to update the daemonset manifest file to add this? I'm happy to create a PR to add it

**Comment by keitwb** [comment]
Yes, that would be fine if you wanted to add it.  Thanks.  Closing this for now.
