### ISSUE TITLE
postgresql monitor

### ISSUE THREAD

**Issue by jyotsnavish** [signalfx/signalfx-agent#1495]
Is this supported on linux and windows agent both?

**Comment by xp-1000** [comment]
hello @jyotsnavish 

- https://docs.signalfx.com/en/latest/integrations/agent/monitors/postgresql.html is basically a wrapper around https://docs.signalfx.com/en/latest/integrations/agent/monitors/sql.html monitor which is a pure go implementation into signalfx agent so it should work on both windows and linux
- https://docs.signalfx.com/en/latest/integrations/agent/monitors/collectd-postgresql.html is a collectd based monitor so it will only work on linux while collectd only support linux

**Comment by keitwb** [comment]
Yes, as @xp-1000 said, it is supported on both Windows and Linux.  Please open another ticket if you have any trouble with it.
