### ISSUE TITLE
error No such property: signalfx on jmx monitor

### ISSUE THREAD

**Issue by xp-1000** [signalfx/signalfx-agent#1497]
Hello,

I don't manage to make the jmx monitor to works.

I tried to implement tomcat metrics from this monitor creating a groovy script.

But no matter what I try I got following error:

```
error msg="Error gathering JMX metrics\ngroovy.lang.MissingPropertyException: No such property: signalfx for class: Script1"
```

I even tested your sample script from https://docs.signalfx.com/en/latest/integrations/agent/monitors/jmx.html on cassandra jmx and same result.

**Comment by keitwb** [comment]
Hi @xp-1000, this is quite strange.  We recently upgraded the bundled JRE to Java 11 which might be a problem, but there also isn't anywhere we have a property called `signalfx` (lowercase).  We'll try and reproduce and get to the bottom of it.

**Comment by xp-1000** [comment]
hello @keitwb any news on this?

**Comment by keitwb** [comment]
@jchengsfx and I both tried to reproduce this and couldn't (it seemed to work fine).  Can you explain how you are deploying the agent and the config you are using?  I'm guessing it's environmental.

**Comment by xp-1000** [comment]
Ah ok thanks for feedback, I will try again with latest version and provide every relevant resources.

**Comment by xp-1000** [comment]
Ok I found my old test env and check again to reproduce the error.

> level=error msg="Error gathering JMX metrics\ngroovy.lang.MissingPropertyException: No such property: signalfx for class: Script1" createdTime=1.605294969435e+12 lineno=0 logger=com.signalfx.agent.jmx.JMXMonitor sourcePath="com.signalfx.agent.jmx.JMXMonitor:lambda$configure$0"

the monitor config is:

```yaml
-   type: jmx
    host: localhost
    port: 7199
    groovyScript: /etc/signalfx/cassandra.groovy
```

and the groovy script is simply copy paste from https://docs.signalfx.com/en/latest/integrations/agent/monitors/jmx.html

the version of the agent:

```bash
$ signalfx-agent --version
agent-version: 5.5.4, collectd-version: 5.8.0-sfx0
```

**Comment by xp-1000** [comment]
I also tested jmx which works fine:

```bash
$ echo 'bean org.apache.cassandra.db:type=StorageService' | java -jar jmxterm-1.0.2-uber.jar -l 127.0.0.1:7199 -n
Welcome to JMX terminal. Type "help" for available commands.
#bean is set to org.apache.cassandra.db:type=StorageService
```

**Comment by xp-1000** [comment]
I am just stupid ...

changed:

`groovyScript: "/etc/signalfx/cassandra.groovy"`

to: 

`groovyScript: {"#from": "/etc/signalfx/cassandra.groovy", raw: true}`

it works fine sorry for the inconvenience

**Comment by keitwb** [comment]
oh wow that was kind of tricky...I also forgot that that is the raw script and not the path.  I guess groovy was trying to do division or something.

**Comment by xp-1000** [comment]
I did not find an easy way to log / debug "in live" so I log into a separate file from the groovy script for now.
This monitor gives a very flexible way to collect jmx metrics but also add rich context with dimensions.
I am not sure about the perf / usage of groovy inside the agent but it is pretty awesome in term of capabilities ^^
If the smart agent would not have been deprecated soon I think I would tried to rewrite cassandra and tomcat monitors (currently based on genericjmx) with this new monitor :p
