### ISSUE TITLE
signalfx-agent does not discover service ports

### ISSUE THREAD

**Issue by alexxed** [signalfx/signalfx-agent#1508]
[operator-sdk provides metrics through a service](https://v0-19-x.sdk.operatorframework.io/docs/golang/legacy/monitoring/prometheus/), so the metrics ports are not on the container spec of the pod, thus signalfx-agent can't find them. 

I tried via discoveryRule in the agent config and via pod annotations. Then looked into the code and saw that k8sutil indeed only looks at container ports when using annotations. Also [docs](https://docs.signalfx.com/en/latest/integrations/agent/auto-discovery.html) say "Examples of targets are an open TCP port on a container, or a Kubernetes Node, or a listening TCP socket on localhost. ", so this rules out service ports.

Is this a known limitation or can this work in any way?

**Comment by keitwb** [comment]
You can specify additional ports in the k8s pod annotations of the operator-sdk pod like this:

`agent.signalfx.com/monitorType.8383: "prometheus-exporter"`

It will make the agent see that port and configure a prometheus-exporter monitor automatically for that pod even though port 8383 isn't defined in the container port list.  This assumes you have the `k8s-api` observer active.

See https://docs.signalfx.com/en/latest/integrations/kubernetes/k8s-monitors-observers.html#configuring-the-observer-using-kubernetes-annotations for more annotations if you need additional config for the prometheus-exporter monitor.

Let me know if you are still having issues after trying that.

**Comment by alexxed** [comment]
Yes, that's what I was using, I ended up exposing them as container ports and that works, but let me check again with service ports only.

**Comment by alexxed** [comment]
Tried again, doesn't work, and couldn't as far as I read the code: https://github.com/signalfx/signalfx-agent/blob/c295133b4a52b2fff071c8070536183a48e403fc/pkg/observers/kubernetes/annotations.go#L89-L94

Here are some details:
```
# kubectl get service xxx-operator-metrics -o yaml
apiVersion: v1
kind: Service
metadata:
  [snip]
spec:
  clusterIP: 10.152.183.153
  ports:
  - name: http-metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  - name: cr-metrics
    port: 8686
    protocol: TCP
    targetPort: 8686
  selector:
    name: xxx-operator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

```
{"error":"kubernetes config annotation agent.signalfx.com/monitorType.8383 references invalid port number 8383","level":"error","msg":"Invalid K8s agent annotation","time":"2020-10-27T08:29:57Z"}
```

```
bash-4.3# cat /etc/signalfx/agent.yaml | grep k8s-api -A 3
- type: k8s-api
  discoverAllPods: false
  discoverNodes: false

# signalfx-agent status monitors | grep 8383
# shows nothing
```

**Comment by keitwb** [comment]
Ok, yeah you're right it does have to be in the ports.  Look at the `additionalPortAnnotations` config in https://github.com/signalfx/signalfx-agent/blob/master/docs/observers/k8s-api.md#configuration and see if that works for your use case.  I think you can just put an annotation like `prometheus.io/port: 8383` and then put the config `additionalPortAnnotations: ["prometheus.io/port]" on the k8s-api observer and then you can use discovery rules like normal (not the pod annotation config stuff).

**Comment by alexxed** [comment]
Thank you @keitwb, that works:
```
additionalPortAnnotations:
  - prometheus.io/port
monitors:
  - type: prometheus-exporter
    discoveryRule: port == 8383
    metricPath: /metrics
    extraDimensions:
      metric_source: operator-sdk-metrics
```

It's not ideal, using sfx annotations looks cleaner than adding a bunch of discover rules, but at least there's a way to make it work without setting container ports.

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
