### ISSUE TITLE
Pass arguments to python script from agent.yaml

### ISSUE THREAD

**Issue by aishvaryaps** [signalfx/signalfx-agent#1510]
can we pass arguments from agent.yaml file ?
Example:
agent config is as follows:
```

  - type: python-monitor
    scriptFilePath: /etc/signalfx/demo.py   "hello" 10

```

Here, hello and 10 are arguments that i need to pass to python script from the agent.yaml file..
what is the correct syntax ?
when i configure the:
**scriptFilePath: /etc/signalfx/demo.py   "hello" 10** 
The metric stops reporting in signalfx

**Comment by keitwb** [comment]
Hi, there isn't really any mechanism for passing exec args to the script.

The recommended thing to do is to add addition configuration to the `python-monitor` config and it will be passed to the Python script's `run`/`configure` function within the `config` parameter.

E.g.

```yaml
- type: python-monitor
  scriptFilePath: /etc/signalfx/demo.py
  command: "hello"
  count: 10
```

`command` and `count` are arbitrary names that can be anything you want.  They will appear in the `config` dict when your monitor  script is instantiated by the agent.

**Comment by aishvaryaps** [comment]
Thanks Keith,

I have configured the agent.yaml as mentioned by you
```
- type: python-monitor
  scriptFilePath: /etc/signalfx/demo.py
  command: "hello"
  count: 10
```

How do I read those params in python script file ?

I tried with sys.argv[1] and also I tried to print config.. to see the typeof config (if its object format or string)
Could you please provide with some guidance as in how to read those params in python script file
In this case for example , how do I read value of command (i.e hello)

**Comment by keitwb** [comment]
Post me the content of your `demo.py` and I'll show you where it can be accessed.

**Comment by keitwb** [comment]
If you need a sample Python script, look at https://github.com/signalfx/signalfx-agent/blob/master/python/sample/monitor_simple.py.

**Comment by aishvaryaps** [comment]
Hi ..
contents of demo.py are below
We are checking if a particular Port is up and running via oython script
need to pass IP and port from agent.yaml
```
import socket
import sys

ip = "172.31.55.158"
port = 3389

#ip = sys.argv[1]
#port = int(sys.argv[2])

a_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
result_of_check = a_socket.connect_ex((ip, port))
if result_of_check == 0:
    print("Port is open")
    check = 100
else:
    check = 0
    print("Port is not open")
    a_socket.close()

print(check)

def run(config, output):
    print(check)
    output.send_gauge("remote_port", check)

```

**Comment by keitwb** [comment]
ok, the `config` argument to `run` is a dictionary that contains the additional config you put on the monitor config for the agent.  So you could access it with `config.get("hello")`, etc.

Also you need to put the socket stuff _inside_ the run function so that it gets invoked on a regular interval.  The script does not get reloaded every cycle, it gets loaded once at agent startup and the run function is called repeatedly.

**Comment by keitwb** [comment]
Also for `ip` you should use the standard `host` config option, which can also be accessed the same way (i.e. `config.get("host")`

**Comment by aishvaryaps** [comment]
Thank you ..
This works for me..
