### ISSUE TITLE
Ignore dimension from discovery rule

### ISSUE THREAD

**Issue by xp-1000** [signalfx/signalfx-agent#1514]
Hello,

When using discovery rules, some dimensions related to the endpoint are automatically added to metrics coming from the monitor.

I know there is `extraDimensionsFromEndpoint` option to map other info as dimensions.

My question is about to do the reverse: I would like to prevent the agent to add some dimension from endpoints.

For example using `hostport` observer will lead to `pid` dimension added to metrics.

The reason is I would like to avoid explicitly aggregate all others dimensions (except pid) in heartbeat detector, else it will raise alert for each restart of the process.

Using `disableEndpointDimensions: true` will also remove all other dimensions we would like to keep.

**Comment by xp-1000** [comment]
Oh my bad I just found it is possible with `dimensionTransformations` (and documented):

> Note that it is possible to remove unwanted dimensions via this configuration, by making the desired dimension name an empty string.

**Comment by keitwb** [comment]
Oh nice, yeah I forgot you can technically delete dimensions with that.  I think that was an "unintended behavior" discovered after the fact but we've solidified it as officially supported so you can rely on it.
