### ISSUE TITLE
 name: Install signalfx-agent via yum package manager   yum:

### ISSUE THREAD

**Issue by sukhsehaj** [signalfx/signalfx-agent#1525]

**Comment by sukhsehaj** [comment]
This step is not executing, I am getting the following error:

TASK [../roles/ansible-signalfx : Install signalfx-agent via yum package manager] **************************************************************************************************************************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|succeeded` use `result is succeeded`. This feature will be removed in version 2.9. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
FAILED - RETRYING: Install signalfx-agent via yum package manager (5 retries left).
FAILED - RETRYING: Install signalfx-agent via yum package manager (4 retries left).
FAILED - RETRYING: Install signalfx-agent via yum package manager (3 retries left).
FAILED - RETRYING: Install signalfx-agent via yum package manager (2 retries left).
FAILED - RETRYING: Install signalfx-agent via yum package manager (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 5, "changed": false, "msg": "https://dl.signalfx.com/signalfx-agent-rpm/final/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden\nTrying other mirror.\n\n\n One of the configured repositories failed (SignalFx Agent Repository),\n and yum doesn't have enough cached data to continue. At this point the only\n safe thing yum can do is fail. There are a few ways to work \"fix\" this:\n\n     1. Contact the upstream for the repository and get them to fix the problem.\n\n     2. Reconfigure the baseurl/etc. for the repository, to point to a working\n        upstream. This is most often useful if you are using a newer\n        distribution release than is supported by the repository (and the\n        packages for the previous distribution release still work).\n\n     3. Run the command with the repository temporarily disabled\n            yum --disablerepo=signalfx-agent ...\n\n     4. Disable the repository permanently, so yum won't use it by default. Yum\n        will then just ignore the repository until you permanently enable it\n        again or use --enablerepo for temporary usage:\n\n            yum-config-manager --disable signalfx-agent\n        or\n            subscription-manager repos --disable=signalfx-agent\n\n     5. Configure the failing repository to be skipped, if it is unavailable.\n        Note that yum will try to contact the repo. when it runs most commands,\n        so will have to try and fail each time (and thus. yum will be be much\n        slower). If it is a very temporary problem though, this is often a nice\n        compromise:\n\n            yum-config-manager --save --setopt=signalfx-agent.skip_if_unavailable=true\n\nfailure: repodata/repomd.xml from signalfx-agent: [Errno 256] No more mirrors to try.\nhttps://dl.signalfx.com/signalfx-agent-rpm/final/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden\n", "rc": 1, "results": []}
	to retry, use: --limit @/home/teamcity/ansible_controller/plays/ops_install_signalfx.retry

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=10   changed=0    unreachable=0    failed=1

**Comment by jchengsfx** [comment]
@sukhsehaj Please provide details if you are still experiencing any problems, otherwise this issue will be closed.  Also, check https://github.com/signalfx/signalfx-agent/blob/master/docs/agent-install-packages.md#install-using-rpm and https://github.com/signalfx/signalfx-agent/blob/master/docs/deb-rpm-repo-migration.md#rpm for agent installation instructions with yum.

**Comment by sukhsehaj** [comment]
The issue can be closed. I am good.

Thank you.

**Comment by jchengsfx** [comment]
Thanks @sukhsehaj!
