### ISSUE TITLE
Kubernetes Windows Node Support

### ISSUE THREAD

**Issue by matthewmodestino** [signalfx/signalfx-agent#1548]
Hi team I am getting asked more frequently about kubernetes windows nodes and compatibility with smart agent. 

Can you please advise? Any plans to support windows k8s nodes?

**Comment by dloucasfx** [comment]
Check https://github.com/signalfx/signalfx-agent/tree/master/deployments/k8s/helm/signalfx-agent#windows

**Comment by matthewmodestino** [comment]
Nice, is this officially supported? Who needs to update integrations page or k8s docs?

**Comment by keitwb** [comment]
Best doc is here: https://github.com/signalfx/signalfx-agent/tree/master/deployments/k8s/helm/signalfx-agent#windows

We aren't advertising it too much until it is better proven.
