### ISSUE TITLE
Unable to Set Global Span Tags with Chart

### ISSUE THREAD

**Issue by timothymathison** [signalfx/signalfx-agent#1564]
As far as I can tell there is no way to set the the `globalSpanTags` parameter for `agent.yaml`, without [overriding the entire agent config with the `agentConfig` value](https://github.com/signalfx/signalfx-agent/blob/2f64be5613ca0b6937d22e4222ece0349477e8d5/deployments/k8s/helm/signalfx-agent/templates/configmap.yaml#L15)?

Would it be possible to add a `globalSpanTags` value to the chart similar to the existing [`globalDimensions` value](https://github.com/signalfx/signalfx-agent/blob/f3147854c36c45a7d73e52f4b94f57a83381df19/deployments/k8s/helm/signalfx-agent/values.yaml#L42)?

**Comment by keitwb** [comment]
Yes, that is a useful feature.  PRs are welcome!

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
