### ISSUE TITLE
Split repo per usage

### ISSUE THREAD

**Issue by fe80** [signalfx/signalfx-agent#1568]
Hi,

It's possible to split repo per usage ?

It's complicated to related a forge release (I thinking about puppet for my case) with a git tag on this big repository.

Regards,

**Comment by keitwb** [comment]
Can you explain your forge release process and what aspects of the repo are complicating it?  I can perhaps offer some tips on how to make it easier based on our own experience.

**Comment by fe80** [comment]
With Puppet we deploy with r10k. With this puppet tools we can directly deploy the forge module (by the tar.gz), or clone per repo with commit, tags, branch... (I don't have check if I can clone a sub repository from about a git repo with pdk it's the first time have this workflow)

In my case we clone the code per remote and keep the git history on internal git for deploy on multiple puppet server (+- 10).

I'm really confused about this repository management, we need apply filter for check log, issue, commit, etc... (It's maybe just me)

**Comment by fe80** [comment]
Ps: I've a tool who can check if new release is available with the repo projet and create internal pull request. I can't use my tool with this repo, maybe I'm not alone in this case

**Comment by keitwb** [comment]
We do push the puppet module to the puppet forge at https://forge.puppet.com/modules/signalfx/signalfx_agent.  It should be fairly up to date with the repo.  Can you just use that?  It should be the same as what is from the repo, and we can update it if not.

**Comment by flands** [comment]
Hey everyone -- puppet for the agent is part of the release process today. If there is something missing in the puppet packaging, please open an issue.
