### ISSUE TITLE
Cutom labels for kubernetes metrics

### ISSUE THREAD

**Issue by VarsChdhry** [signalfx/signalfx-agent#1578]
We have SFX smart agent running as daemonset on kubernetes nodes and we are sending metrics to Splunk, and looking if we can get pods and nodes metadata labels as metrics tags/label/dimensions? 

I have been through some of SFX doc about dimensions/tags/properties, but it doesn’t state about how SFX agent can pick pods and nodes metadata labels as tags for metrics, or I might be missing something?

we have podname, namespace, kubernetes-cluster, pod_id as dimensions for metrics that are coming into Splunk, but we have additional labels such as service-tier, env etc in pods/nodes metadata and we would like to add them as metrics dimensions/tags.

**Comment by mstumpfx** [comment]
Hi @VarsChdhry 

We do automatically sync pod and node labels but they are synced as properties onto the `kubernetes_node_uid` and `kubernetes_pod_uid` dimensions. This is slightly buried in our documentation. It is the `kubernetes-cluster` monitor that does the label syncing:
https://docs.signalfx.com/en/latest/integrations/agent/monitors/kubernetes-cluster.html#properties

If you want to see what properties are synced to each dimension, you can find the dimension in the metadata catalog in the UI (upper right corner dropdown menu --> Metadata catalog) and then search for either `kubernetes_pod_uid` or `kubernetes_node_uid` and find the respective value. 

You can also use the API to query for this info - https://dev.splunk.com/observability/reference/api/metrics_metadata/latest#endpoint-retrieve-dimension-metadata-name-value

And somewhat related that you might find useful - you can actually use labels on pods to configure the smart agent: https://docs.signalfx.com/en/latest/integrations/kubernetes/k8s-monitors-observers.html#configuring-the-observer-using-kubernetes-annotations

**Comment by VarsChdhry** [comment]
Hi @mstumpfx

Thank you for quick response!!
As you said above that pod and node labels are synced as properties onto **kubernetes_node_uid**, and I think our SFX daemonset is trying to pick them such as appname, servicetier,env but we have error in updating the dimension
` level=error msg="Unable to update dimension, retrying" dim="{name: \"kubernetes_node_uid\"; value: \"node-id-abc\"; props: map[agentpool:agentpool beta_kubernetes_io_arch:amd64 beta_kubernetes_io_instance-type:Std beta_kubernetes_io_os:linux Env:abc KubernetesCluster:xyz-cluster Location: loc-name ServiceTier:test  cluster:cluster-name hostname:vm001 kubernetes-os:linux kubernetes-node:node-test ; tags: map[node-role_kubernetes_io_agent:true]; mergeIntoExisting: false}" error="error making HTTP request to https://api.us0.signalfx.com/dimension/kubernetes_node_uid/node-id-abc: Put \"https://api.us0.signalfx.com/dimension/kubernetes_node_uid/node-id-abc\": EOF" url="https://api.us0.signalfx.com/dimension/kubernetes_node_uid/node-id-abc"`
we have similar issue with **kubernetes_pod_uid kubernetes_uid container_id**

**Comment by keitwb** [comment]
@VarsChdhry are you sure your network firewall is configured to allow these requests  outbound?  Also does the error repeat in the logs or is it just temporary?  As the log indicates,  it will retry network  issues such as the one you are seeing.

**Comment by VarsChdhry** [comment]
Network firewall seems to be configured or I might be missing something, and yes error repeats.

**Comment by VarsChdhry** [comment]
@keitwb we have these metrics going to Splunk and we would like to have pods and nodes metadata as dimensions, so that we can split metrics based on it. SFX agent can do that ? as in it can send to SFX UI like said earlier metadata would be synced as properties, how about Splunk? Can we send metadata as Dimensions for metrics in Splunk?

**Comment by VarsChdhry** [comment]
Hey so we tried to add something like below under SFX monitor in configmap
extraDimensions: 
      ServiceTier: ‘Get(container_labels, “myapp.com/environment”)’ 

so that we can get pods labels as dimensions,  what we got in Splunk is ServiceTier as dimension and literally “ Get(container_labels, “myapp.com/environment” as it’s value, doing something wrong here?

**Comment by keitwb** [comment]
Change `extraDimensions` to `extraDimensionFromEndpoint` and I think what you are trying should work.  Plain `extraDimensions` just interprets the value as a string and doesn't evaluate it.

**Comment by VarsChdhry** [comment]
We tried using` extraDimensionFromEndpoint` And received error
`msg="Could not process configuration for monitor" error="unknown name container_labels (1:5)\n | Get(container_labels, \"myapp.com/environment\")\n | ....^" monitorType=kubernetes-cluster`

**Comment by keitwb** [comment]
Are you using a `discoveryRule` with the monitor?

**Comment by VarsChdhry** [comment]
Hey so we are trying to add it under `kubernetes-cluster` monitor, and in SFX doc we don’t see having `discoveryRule` for this monitor https://docs.signalfx.com/en/latest/integrations/agent/monitors/kubernetes-cluster.html

**Comment by keitwb** [comment]
Ah ok, so for that you will already get the container labels placed as properties on the pod metrics associated with that pod.  The property name will be sanitized as `myapp_com_environment` since our system doesn't allow `.` or `/` in property names.  You should be able to use that in charts and detectors.

**Comment by VarsChdhry** [comment]
Thank you @keitwb but we aren’t getting any ` kubernetes-cluster` Metrics ingested in Splunk because we added `extraDimensionsFromEndpoint` For same monitor and we are having same error log as mentioned above. 

Even if we have container labels placed as properties on the pod metrics associated with that pod, as metrics aren’t in Splunk we cannot verify if there are any associated properties with metrics.

**Comment by keitwb** [comment]
Yes, you will have to remove the `extraDimensions*` config options.  There is nothing special you have to do  to get the pod properties.

**Comment by VarsChdhry** [comment]
Hi @keitwb we are specifically looking that if we can get pods labels as dimensions into Splunk for metrics. So specific question would be like “
Do kubernetes labels show up as Dimensions on SPLUNK metrics or do they only show up in SignalFX?” 

As you said that “There is nothing special you have to do to get the pod properties “ but that might just apply for sending metrics to SignalFX, we would like to have pods labels as Dimensions in Splunk using signalfx agent.

**Comment by somensari-splunk** [comment]
@VarsChdhry , can you confirm if you can see the labels as dimensions on SFX? From your last response, it sounds like you want to consume the SFX metrics (with labels/dimensions) on the Splunk side... if that's the case, we probably need to close this issue here and talk to the Splunk Core team

**Comment by dloucasfx** [comment]
As we have discussed internally:

Labels , which are treated as properties are not pushed to splunk metrics by the "splunk" writer.

In details, the dimension object in SFX is more involved, one of the fields of that object is called properties. Properties are sent and updated asynchronously and independently of a datapoint and they target a specific/unique dimension.

Back to your problem, the pod and node labels, as explained in @mstumpfx comment, are properties that are part of kubernetes_pod_uid:<value> or kubernetes_node_uid:<value> unique dimension object

The Splunk writer deals with the datapoint struct which does not have access to the properties field, however, it does contain metadata and dimensions (Note: the dimension in the datapoint struct is not the full SFX dimension struct I mentioned earlier, it’s just a key-value pair map, example kubernetes_pod_uid:<value> ). 
The dimension and metadata are sent to splunk as  `Fields` https://github.com/signalfx/signalfx-agent/blob/18723299ba971113da4d93120c98db92a2a19d7e/pkg/core/writer/splunk/splunk.go#L181-L189

Making the labels/properties available to Splunk writer would be an enhancement.

Hope this answers your question.
