### ISSUE TITLE
Windows install still not idempotent

### ISSUE THREAD

**Issue by pearcec** [signalfx/signalfx-agent#1584]
https://github.com/signalfx/signalfx-agent/blob/e2ff35fa932c376ce8ed215cf707ec7bda48d15c/deployments/puppet/manifests/win_repo.pp#L19

file and find_file execute on the server not the agent.

**Comment by pearcec** [comment]
You need to write a fact.  Something like this.  Make sure you get the correct path and set a version and not a url in the version.txt.

```
Facter.add(:signalfx_agent_version) do
    confine :osfamily => "Windows"
    setcode 'type "C:\\Program Files\\SignalFx\\version.txt"'
  end
```

**Comment by jchengsfx** [comment]
Thanks @pearcec.  Was thinking the same about adding the new fact.

**Comment by jchengsfx** [comment]
@pearcec v1.2.0 has been released to puppet forge.  Please let us know if the changes address this issue.

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
