### ISSUE TITLE
Incorrect usage of package causes constant reporting

### ISSUE THREAD

**Issue by pearcec** [signalfx/signalfx-agent#1588]
https://github.com/signalfx/signalfx-agent/blob/89ea2abe91b1ed64fcdd295e2fdfbeaafa6db2cd/deployments/puppet/manifests/init.pp#L36

The use of package in this context is not installing the package.  It is simply installing the service.  There IS a service resource type, or you could use exec.  Using the package in this way constant runs this install.  Why? Because you executable doesn't actually install as a windows package.  So when puppet looks for an installed package it sees it as absent and run this command over and over again.

Notice: /Stage[main]/Signalfx_agent/Package[signalfx-agent]/ensure: created

If you moved to an installed package this might solve a lot of pain. Including this issue

https://github.com/signalfx/signalfx-agent/issues/1584

**Comment by jchengsfx** [comment]
@pearcec v1.2.0 has been released to puppet forge.  Please let us know if the changes address this issue.

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
