### ISSUE TITLE
how to run the signalfx-agent user in exec to run oracle DB script.

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1601]
We are trying to run the DB script from agent.yaml file with the "signalfx-agent" user so that we can send the custom metric data to Signalfx console. But "signalfx-user" is a OS user with which we are not able to run the DB script. So we want to know how we can run the script with different user apart from "signalfx-agent" user?

Below is the configuration we have set in the agent.yaml file:

  - type: collectd/custom
    template: |
      LoadPlugin exec
      <Plugin exec>
        Exec "signalfx-agent" "/etc/signalfx/test.sh"
      </Plugin>

Error:  Feb 11 13:41:03 server signalfx-agent: time="2021-02-11T13:41:03Z" level=error msg="exec plugin: Unable to parse command, ignoring line: \"TNS:could not\"" collectdInstance=monitor-10

**Comment by keitwb** [comment]
@RPooja08 do you mind sharing the contents of the `test.sh` script?

**Comment by RPooja08** [comment]
Sure I can share the script. Please find below:

#!/bin/bash

export ORACLE_BASE=/u01/app/oracle
export ORACLE_HOME=/u01/app/oracle/product/12.1.0/dbhome_1
export PATH=$PATH:$ORACLE_HOME/bin
export ORACLE_SID=DBNAME

FILE=/etc/signalfx/sqlfile1.sql
INTERVAL="${COLLECTD_INTERVAL:-60}"
HOSTNAME="${COLLECTD_HOSTNAME:-localhost}"
DB="$(sqlplus -S user/password@DB_SID @/etc/signalfx/sqlfile1.sql | awk '{print $1}')"
DBCol=$(sqlplus -S user/password@DB_SID @/etc/signalfx/sqlfile1.sql | awk '{print $2  " " $3}')
OpenMode="READ WRITE"

if [ "$OpenMode" == "$DBCol" ]
then
   VALUE=1
   echo "PUTVAL \"HOSTNAME-demo/exec/gauge-openmode\" interval=$INTERVAL N:$VALUE"
fi

**Comment by keitwb** [comment]
I suspect there is an issue with the output of the `sqlplus` command.  It looks like the line it could not parse (`TNS:could not`) comes from that command.

I would actually recommend that you use the `python-monitor` instead (https://github.com/signalfx/signalfx-agent/blob/master/docs/monitors/python-monitor.md), as it is much more powerful and less picky about stdout pollution.

**Comment by RPooja08** [comment]
It is working for me now. There was the issue with the database user.
