### ISSUE TITLE
Filter option for VMWare monitor not working

### ISSUE THREAD

**Issue by stevehut72** [signalfx/signalfx-agent#1605]
We are trying to monitor one data cluster within one of our two datacentres with signalfx using the filter option.

We have followed https://docs.signalfx.com/en/latest/integrations/agent/monitors/vsphere.html and used a variation of the example filter - "Datacenter == 'MyDatacenter' && Cluster == 'MyCluster'". 

The instructions state "The above expr value will cause metrics collection for only the given datacentre + cluster. "  which has worked for the specified datacentre in our filter but it has brought in all the clusters on a second datacentre in the VMWare infrastructure.  Is there an issue with the filter option ?

Thanks

Steve

**Comment by pmcollins** [comment]
Hi Steve, sorry this isn't working for you. I'm assuming your filter expression is exactly `Datacenter == 'MyDatacenter' && Cluster == 'MyCluster'` with just the names of the datacenter and cluster replaced, correct?

Do you see anything in the logs that says `shouldFollowCluster failed`? (If the expression engine fails for any reason, it defaults to not filtering out the cluster)

Does the cluster for which you want metrics have a unique name? If so, can you try just "Cluster == 'MyCluster'"?

Thanks.

**Comment by stevehut72** [comment]
Hi Pablo thanks for getting back to me. Yes we have specifically named the datacentre and cluster in the filter definition and the cluster does have a unique name.  This works for the specified datacentre, the issue is signalfx if bringing in all the clusters from the second datacentre, which has a different name and has not been specified in the filter.

We checked the logs and there is no entry for “shouldFollowCluster failed”

Thanks

Steve

**Comment by rcastley** [comment]
@stevehut72 It looks like Pablo submitted a fix for this issue. This will be rolled into the next agent release.

Cheers,
- Robert

**Comment by stevehut72** [comment]
Thanks Robert

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
