### ISSUE TITLE
Winperfmon Reports error when filtered instance not found

### ISSUE THREAD

**Issue by mcmiv413** [signalfx/signalfx-agent#1613]
https://github.com/signalfx/signalfx-agent/tree/master/pkg/monitors/telegraf/monitors/winperfcounters 

We are applying custom dimensions to certain services and what we have found is that winperfmon will throw errors if the specific instance it is looking for is not present and will do so repeatedly for each interval, this seems like a bug to me.

**Comment by dloucasfx** [comment]
@mcmiv413 
Just to make sure I understand the problem, the instance you are looking for does not exist and the agent is logging this error message on every poll?
(Actual error message) + `an error occurred while gathering metrics` 

If this is the case, the agent just relates the error returned by telegraf and we don't want to filter out those errors.

**Comment by mcmiv413** [comment]
Yes, I have multiple windows perf mon agents packaged and shipped and for each one it will complain that it doesn’t exist if it is not found for each interval cycle

**Comment by dloucasfx** [comment]
I don't think we need to change the behavior here, these error messages don't have specific types and it will unreliable to filter by string.
@keitwb WDYT?

**Comment by mcmiv413** [comment]
This same type of behavior would happen if an instance stopped existing, if a service was stopped, if we wanted to get perfmon metrics on instances of powershell, etc, etc.

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
