### ISSUE TITLE
Is ping monitoring possible from signalfx?

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1614]
Can we do ping monitoring anyway from signalfx?

**Comment by rcastley** [comment]
You could use https://github.com/signalfx/signalfx-agent/blob/master/docs/monitors/http.md or use the the collectd bundle ping monitor e.g.
```  - type: collectd/custom
    template: |
      LoadPlugin ping
      <Plugin "ping">
        Host "1.1.1.1"
      </Plugin>
  ```

**Comment by RPooja08** [comment]
So we have to add above piece of code on every server to ping its own IP?

**Comment by RPooja08** [comment]
Do we have any setup with which we can perform ping monitoring from the Windows server?

**Comment by keitwb** [comment]
The collectd ping plugin won't work on Windows, so you will have to rely on a custom script.  The python-monitor works on Windows and you could probably even share the same script between Windows and Linux.

**Comment by RPooja08** [comment]
Thank you @keitwb, I will try with the python-monitor plugin.
