### ISSUE TITLE
Signalfx service is not getting auto start post server reboot sometimes.

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1616]
There is many times when server reboot is happing and for random servers the signalfx agent is not getting auto restart on a windows server. While checking port before starting the agent, the port (8095) was free and not reserved by any other application.
Post agent start there were no error captured in logs.

**Comment by dloucasfx** [comment]
@RPooja08 
Please provide more info:
- OS
- Agent version
- Logs after the restart

**Comment by RPooja08** [comment]
Please find the details below:
OS: windows-server-2016
Agent Version:  5.8.0
Logs after the restart are as below:

[logs.txt](https://github.com/signalfx/signalfx-agent/files/6066415/logs.txt)

**Comment by dloucasfx** [comment]
@RPooja08 
Thanks for the info and logs.
In the logs, the agent version is showing up as `5.3.0` and you have mentioned `5.8.0` , I just want to make sure we are looking at the right instance.
```
Information	2/26/2021 7:20:24 AM	signalfx-agent	1	None	"time=""2021-02-26T07:20:24-05:00"" level=info msg=""Starting up agent version 5.3.0""
```

Can you run this and send us the output
```
Get-Service -Name signalfx-agent | Select-Object *
```

**Comment by RPooja08** [comment]
Hi Dani, I have pulled the agent version for this CI from Signalfx console. Let me get the output of a command and share with you.

**Comment by RPooja08** [comment]
Here is the output of a command:

PS C:\Windows\system32> Get-Service -Name signalfx-agent | Select-Object *

Name                : signalfx-agent
RequiredServices    : {}
CanPauseAndContinue : False
CanShutdown         : True
CanStop             : True
DisplayName         : SignalFx Smart Agent
DependentServices   : {}
MachineName         : .
ServiceName         : signalfx-agent
ServicesDependedOn  : {}
ServiceHandle       : SafeServiceHandle
Status              : Running
ServiceType         : Win32OwnProcess
StartType           : Automatic
Site                : 
Container           :

**Comment by RPooja08** [comment]
Hi... Did you find anything.
