### ISSUE TITLE
How can we monitor the port in signalfx?

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1618]
If we do have to check whether port 22 is available to connect or established, How we can monitor this in signalfx?

**Comment by keitwb** [comment]
I would recommend making a simple python script that does this and using the `python-monitor` (https://github.com/signalfx/signalfx-agent/blob/master/docs/monitors/python-monitor.md) to run it and send it in in whatever form you want.  This gives you unlimited flexibility to make the metric whatever you want.

**Comment by RPooja08** [comment]
do we have any other method rather then python monitor.

**Comment by RPooja08** [comment]
I have tried with python monitor, I have updated the agent config with this plugin but I am facing the issue.

Below is the issue description: "The script mentioned in yaml file is not getting refreshed/running. Once the signalfx agent is restarted it will capture the current values from script.The script mentioned in yaml file is not getting refreshed/running. Once the signalfx agent is restarted it will capture the current values from the script."


agent.yaml config:

  - type: python-monitor
    scriptFilePath: /etc/signalfx/remoteport.py
    extraDimensions:
      RemoteHost: "IP_Address"
      Port: 22

Please suggest any findings on this.

**Comment by keitwb** [comment]
Show me the script `remoteport.py` you are using and I can show you how to fix it.

**Comment by RPooja08** [comment]
Below is the script we are using:

import logging
import socket
import sys

logger = logging.getLogger(__name__)

ip = "Server_IP_Adderess"
port = portnumber

a_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
a_socket.settimeout(1)
result_of_check = a_socket.connect_ex((ip, port))

#print(result_of_check)
if result_of_check == 0:
#    print("Port is open")
    check = 100
else:
    check = 0
#    print("Port is not open")
    a_socket.close()

def run(config, output):
    output.send_gauge("remote_port", check)

**Comment by keitwb** [comment]
Ok, you just need to do the logic that sets `check` each time `run` is called, instead of doing it once at module initialization.  Something like this:

```python
import logging
import socket
import sys

logger = logging.getLogger(name)

def run(config, output):
    ip = config["host"]
    port = config["port"]

    a_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    a_socket.settimeout(1)
    result_of_check = a_socket.connect_ex((ip, port))
    if result_of_check == 0:
        check = 100
    else:
        check = 0
    a_socket.close()

    output.send_gauge("remote_port", check, {"target_host": host, "port": str(port)})
```

Notice that I also changed the host/port to be gotten from the `config` dictionary passed in, which means you can reuse the script for different host/port combinations by specifying those as config options in the `python-monitor` config block in your agent config.

Also I added dimensions to the `send_gauge` method which will be helpful in identifying the service in detectors/charts.

Let me know if anything is not clear.

**Comment by RPooja08** [comment]
Thank you so much @keitwb Thank you so much for the detailed info. It helped me a lot to understand the logic.
However, I tried to execute the above script but looks like the function is not getting called.

I am getting the below error in logs:

Mar 19 08:12:09 ip-172-31-41-67 signalfx-agent: time="2021-03-19T08:12:09Z" level=error msg=100 monitorID=11 monitorType=python-monitor runnerPID=18127
Mar 19 08:12:19 ip-172-31-41-67 signalfx-agent: time="2021-03-19T08:12:19Z" level=error msg=100 monitorID=11 monitorType=python-monitor runnerPID=18127
Mar 19 08:12:29 ip-172-31-41-67 signalfx-agent: time="2021-03-19T08:12:29Z" level=error msg=100 monitorID=11 monitorType=python-monitor runnerPID=18127
Mar 19 08:12:39 ip-172-31-41-67 signalfx-agent: time="2021-03-19T08:12:39Z" level=error msg=100 monitorID=11 monitorType=python-monitor runnerPID=18127
Mar 19 08:12:49 ip-172-31-41-67 signalfx-agent: time="2021-03-19T08:12:49Z" level=error msg=100 monitorID=11 monitorType=python-monitor runnerPID=18127
Mar 19 08:12:59 ip-172-31-41-67 signalfx-agent: time="2021-03-19T08:12:59Z" level=error msg=100 monitorID=11 monitorType=python-monitor runnerPID=18127
Mar 19 08:13:09 ip-172-31-41-67 signalfx-agent: time="2021-03-19T08:13:09Z" level=error msg=100 monitorID=11 monitorType=python-monitor runnerPID=18127
Mar 19 08:13:19 ip-172-31-41-67 signalfx-agent: time="2021-03-19T08:13:19Z" level=error msg=100 monitorID=11 monitorType=python-monitor runnerPID=18127
Mar 19 08:13:29 ip-172-31-41-67 signalfx-agent: time="2021-03-19T08:13:29Z" level=error msg=100 monitorID=11 monitorType=python-monitor runnerPID=18127

**Comment by keitwb** [comment]
I think maybe you just have some print statements in the script.  Those will come through as error level by default I believe.  I would take them out once you are done debugging things.

**Comment by RPooja08** [comment]
Yes, I have added a print statement to get the output while running the script manually.
