### ISSUE TITLE
Installation of signalfx-agent.sh fails on arm64

### ISSUE THREAD

**Issue by angelos** [signalfx/signalfx-agent#1619]
### Summary
Installation of signalfx agent using the preferred Linux install method fails with `Unable to locate package signalfx-agent` on our arm-based device.

### Situation

- device: Firefly EC R3328PC
- processor: Cortex A53 (reports as `aarch64`)
- OS: Lubuntu 18.04

### Scenario

When installing using the `https://dl.signalfx.com/signalfx-agent.sh` script, this fails with `Unable to locate package signalfx-agent`. We add the `arm64` architecture to `dpkg` before running the install script, as `arm64` and `aarch64` are compatible.

	user@host:~$ sudo dpkg --add-architecture arm64
	user@host:~$ sudo sh /tmp/signalfx-agent.sh --realm eu0 -- <my-token>
	Ingest URL: https://ingest.eu0.signalfx.com
	API URL: https://api.eu0.signalfx.com
	Trace Endpoint URL: https://ingest.eu0.signalfx.com/v2/trace
	Installing package signalfx-agent (latest) from release repo
	Hit:1 https://download.docker.com/linux/ubuntu bionic InRelease
	Hit:2 http://wiki.t-firefly.com/firefly-rk3399-repo bionic InRelease
	Ign:3 https://splunk.jfrog.io/splunk/signalfx-agent-deb release InRelease
	Hit:4 http://mirrors.aliyun.com/ubuntu-ports bionic InRelease
	Hit:5 http://mirrors.aliyun.com/ubuntu-ports bionic-updates InRelease
	Hit:6 http://mirrors.aliyun.com/ubuntu-ports bionic-backports InRelease
	Hit:7 http://mirrors.aliyun.com/ubuntu-ports bionic-security InRelease
	Hit:8 https://splunk.jfrog.io/splunk/signalfx-agent-deb release Release
	Reading package lists... Done
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	apt-transport-https is already the newest version (1.6.12ubuntu0.9).
	0 upgraded, 0 newly installed, 0 to remove and 68 not upgraded.
	Hit:1 http://mirrors.aliyun.com/ubuntu-ports bionic InRelease
	Hit:2 http://mirrors.aliyun.com/ubuntu-ports bionic-updates InRelease
	Hit:3 http://mirrors.aliyun.com/ubuntu-ports bionic-backports InRelease
	Hit:4 http://mirrors.aliyun.com/ubuntu-ports bionic-security InRelease
	Hit:5 https://download.docker.com/linux/ubuntu bionic InRelease
	Ign:6 https://splunk.jfrog.io/splunk/signalfx-agent-deb release InRelease
	Hit:7 http://wiki.t-firefly.com/firefly-rk3399-repo bionic InRelease
	Hit:8 https://splunk.jfrog.io/splunk/signalfx-agent-deb release Release
	Reading package lists... Done
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	E: Unable to locate package signalfx-agent

(Note that the `Ign:6` above is due to previous installation attempts based on the manual install instruction. The actual `Hit:8` is what is used.

### Hypotheses
It seems the [`https://splunk.jfrog.io/splunk/signalfx-agent-deb`](https://splunk.jfrog.io/splunk/signalfx-agent-deb) has a packaging issue. In the [`dists/release/main/binary-arm64`](https://splunk.jfrog.io/artifactory/signalfx-agent-deb/dists/release/main/binary-arm64/) folder, the [`Packages`](https://splunk.jfrog.io/artifactory/signalfx-agent-deb/dists/release/main/binary-arm64/Packages) file contains references to the `amd64` packages, not `arm64` packages.

	Package: signalfx-agent
	Version: 5.8.0-1
	Architecture: amd64
	Maintainer: SignalFx, Inc. <support+deb@signalfx.com>
	Installed-Size: 521171
	Depends: libcap2-bin
	Section: utils
	Priority: optional
	Homepage: https://signalfx.com
	Description: The SignalFx metric agent
	Filename: pool/signalfx-agent_5.8.0-1_amd64.deb
	SHA1: 9d66063489447428679aff448107ba46b0df98ea
	SHA256: 3078d4c604886f624904fd61e9afdbd17da5fb18b43f21ce66444455e1416ca6
	Size: 138705362

The hashes of this package match with the same version in the [`dists/release/main/binary-amd64`](https://splunk.jfrog.io/artifactory/signalfx-agent-deb/dists/release/main/binary-amd64/) folder. Also, [`/pool`](https://splunk.jfrog.io/artifactory/signalfx-agent-deb/pool/) does not contain any `arm64` packages.

This leads me to two possible hypothesis,
1. there is a `deb` packaging issue, and there actually should be `arm64` packages available, or
2. `arm64` are not intended to be supported by signalFX, and the [`dists/release/main/binary-arm64`](https://splunk.jfrog.io/artifactory/signalfx-agent-deb/dists/release/main/binary-arm64/) folder ended up in the repo by accident.

**Comment by keitwb** [comment]
@angelos your second hypothesis is correct, we don't officially support arm64 so any installation you do for it will have to be setup with your own package infrastructure (or however you prefer to do it).

We try and make the agent compile for arm64 but not much else as we don't yet have any good testing environment for it.
