### ISSUE TITLE
On Azure, agent thinks he is on AWS

### ISSUE THREAD

**Issue by Poil** [signalfx/signalfx-agent#1625]
Hi

Running the agent 5.9.0-1 on Ubuntu 20.04 LTS on Azure

```
Failed to unmarshal AWS instance-identity response" body="<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/>\r\n<title>404 - File or directory not found.</title>\r\n<style type=\"text/css\">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:\"trebuchet MS\", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id=\"header\"><h1>Server Error</h1></div>\r\n<div id=\"content\">\r\n <div class=\"content-container\"><fieldset>\r\n  <h2>404 - File or directory not found.</h2>\r\n  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n" error="invalid character '<' looking for beginning of value"
Mar 10 13:22:36 dpl-prd-vm-1003 systemd-resolved[563]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP
```

This looks like to be a new bug, never had this before from https://github.com/signalfx/signalfx-agent/commit/8b4d34d8efebe975955390b7b5ce108b3ba317b9 @dloucasfx  (before it was hide only available in debug)

Best regards,

**Comment by dloucasfx** [comment]
@Poil this error is benign if you are not on AWS.
The agent is not aware on which infrastructure is running until it collects the resource metadata; the agent always try to pull the metadata from all different cloud providers AWS, GCP and Azure.

Azure and AWS use the same metadata ip server, so the AWS logic makes it all the way to the unmarshal call and fails there, the Azure call will/should make it through and set `azure_resource_id` correctly.

The change you linked was needed as we don't want to mask the error especially if it's coming from AWS

**Comment by Poil** [comment]
It just dirty to have 5 lines of log in our logs, this should be more nicely catch

**Comment by dloucasfx** [comment]
Totally understand.
The problem is that there is no other way to identify the provider type and masking the log messages have been an issue, especially when the errors are legit.
Here is what I will do, I will check for the HTTP status (I believe Azure is returning 404), if it's 404 then we'll print an info message like this `HTTP status 404, assuming not on EC2`, doing so will shortcut the code and return earlier. 

Does this work for you?

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
