### ISSUE TITLE
[RFE] Add possibility to skip adding the yum repo in ansible installation task

### ISSUE THREAD

**Issue by savec80** [signalfx/signalfx-agent#1628]
Hello team,
Can you please look at the possibility to add simple when condition to task:
https://github.com/signalfx/signalfx-agent/blob/master/deployments/ansible/roles/signalfx-agent/tasks/yum_repo.yml#L7
to skip this step if some variable (skip_repo_install for example) is passed?
We would like to utilize your role, though we can't rely on external repo and would like to keep rpm locally.
Thanks.

**Comment by jchengsfx** [comment]
@savec80 The changes have been merged and released to ansible galaxy.  Please try it out and open a new issue if necessary.
