### ISSUE TITLE
Getting error while updating the SQL query in yaml file.

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1631]
We are monitoring the MSSQL database query from agent.yaml file but post updating the file we are getting errors in event logs.
Yaml file config as below:
  - type: sql
    host: localhost:1433
    port: 1433
    dbDriver: sqlserver
    params:
      user: user
      password: "password"

    connectionString: 'sqlserver://user:password@localhost\Instancename:1433?database=master&connection+timeout=30'
    queries:

      - query: "SELECT count(1) as count FROM sys.dm_exec_requests r CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) s where r.total_elapsed_time>7200000 and r.command not like'BACKUP%'and r.command not like 'DBCC%' and s.text not like 'sp_server_diagnostics'"
        metrics:
          - metricName: "DBLongQuery"
            valueColumn: "count"

Error in event logs:

Level	Date and Time	Source	Event ID	Task Category
Error	3/17/2021 4:53:33 AM	signalfx-agent	3	None	"time=""2021-03-17T04:53:33-04:00"" level=error msg=""Problem running SQL query or converting datapoints"" error=""error executing statement SELECT count(1) as count FROM sys.dm_exec_requests r CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) s where r.total_elapsed_time>7200000 and r.command not like'BACKUP%'and r.command not like 'DBCC%' and s.text not like 'sp_server_diagnostics': lookup signalfx: no such host"" monitorType=sql statement=""SELECT count(1) as count FROM sys.dm_exec_requests r CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) s where r.total_elapsed_time>7200000 and r.command not like'BACKUP%'and r.command not like 'DBCC%' and s.text not like 'sp_server_diagnostics'""

Please assist how can I fix the error: lookup signalfx: no such host

**Comment by keitwb** [comment]
@RPooja08 the connection string doesn't appear to be in the right format.  Is the username you are using `signalfx` by chance?

See https://www.connectionstrings.com/sql-server/ for some examples of what a sqlserver connection string would look like.  Try something like that and see if it helps.

**Comment by RPooja08** [comment]
Yes I am using user name as "signalfx"

**Comment by RPooja08** [comment]
Can we use the below connection string with named space?

connectionString: 'sqlserver://user:Password@localhost/InstanceName:1433

**Comment by keitwb** [comment]
No, the connection string is something more like `Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword;` as far as I can tell.  It is different for each type of database, but see https://www.connectionstrings.com/sql-server/ for more examples.

**Comment by RPooja08** [comment]
I have tried with multiple connection strings but still getting the same error.

**Comment by RPooja08** [comment]
I am suspecting the password that can be wrong. The Password starts with the question mark sign "?", is that can cause any issue in connection while defining in the connection string?

**Comment by keitwb** [comment]
Maybe, can you shared the censored connection string you are using, with any sensitive values replaced by `*`?

**Comment by RPooja08** [comment]
I am using the below connection string in which number 1, 3 is working for other DB server.

1.) connectionString: 'sqlserver://user:Password@localhost/MSSQLSERVER01'
2.) connectionString: 'host={{.host}} port={{.port}} dbname=master user={{.user}} password={{.password}} sslmode=disable'
3.) connectionString: 'sqlserver://user:pass@localhost\instancename:1433'
4.) connectionString: 'sqlserver://user:Pass@localhost:1443?database="m"&connection+timeout=30'
5.) sqlserver://loclahost;user=user;password=Pass;encrypt=disable
6.) connectionString: 'sqlserver://TestFX:TestFX@XXXXXX.aws.accenture.com:1433database=master&connection+timeout=30'




connectionString: 'sqlserver://user:Password@localhost/InstanceName:1433

**Comment by RPooja08** [comment]
Is there will be any issue with related to port & dynamic port defined in the SQL network configuration.

**Comment by keitwb** [comment]
The password having a `?` in it could definitely cause problems.  You can try URL escaping it.  If that doesn't work perhaps try regenerating a password without that character (also avoid `&`).

Ports shouldn't be an issue.

**Comment by RPooja08** [comment]
The error we are getting in the SignalFx agent log.

**Comment by RPooja08** [comment]
Receiving below error:
Login error: read tcp 127.0.0.1:51155->127.0.0.1:1433: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by dloucasfx** [comment]
@RPooja08 

Looks like this needs advanced troubleshooting, I recommend to open a support case, this way the issue will be routed through the appropriate channels and it will get a dedicated engineer who will work with you to get the issue resolved.
Make sure to reference this github discussion when you open the support case.

**Comment by RPooja08** [comment]
Thank you so much for the assistance, the issue is resolved now.
