### ISSUE TITLE
Support AWS S3 monitor

### ISSUE THREAD

**Issue by mazzy89** [signalfx/signalfx-agent#1635]
Is there any intention to support AWS S3 as monitor? 

Common use case:

filter for object under an AWS S3 bucket that have not been updated recently.

Is there any interest to implement this?

Should I give a shot in case?

**Comment by keitwb** [comment]
We have not really considered this but it is interesting.  The metrics about objects that haven't been updated recently sounds like it could be a lot of transient MTSs, but general bucket stats like number of objects and total size could be interesting.

We already get object count and bucket size via the CloudWatch hosted integration (not part of the agent but centrally configured), so it isn't really necessary for the agent to get them.

I would recommend making a `python-monitor` script to do what you need and use the AWS python SDK.

**Comment by mazzy89** [comment]
Yes the python monitor script was the immediate second option that I wanted to consider.

Could you elaborate more why having metrics per S3 object is not a good idea? I haven't got what you mean transient MTSs.

**Comment by keitwb** [comment]
> Could you elaborate more why having metrics per S3 object is not a good idea? I haven't got what you mean transient MTSs.

I mean if you have a ton of objects in a bucket, each one would be a timeseries.  Moreover if the objects were short-lived and had a high churn rate, there could be a ton of short-lived (transient) timeseries, which are kind of hard to detect on.

What problem are you trying to solve though?  If you are trying to check for old, unused items, you could in theory just have the python-monitor script figure out the oldest item in a bucket and send a metric with the bucket name as a dimension but not the object name.  I'm assuming you probably don't care so much about the specific *name* of the object as much as the fact that it is old, and when somebody goes into the bucket to do maintenance they can see the name very easily at that point.  The biggest thing is to determine the problem you want to solve and the remediation steps you would do.  That will drive what dimensions and how much resolution you need.

**Comment by mazzy89** [comment]
@keitwb I think I agree with you. You clarified well the tradeoff and having then an integration that pull all the objects would create a lot of transient metrics.

I think we can close this unless someone has any other doubts. thanks

**Comment by keitwb** [comment]
Ok, let me know if you have any further questions.
