### ISSUE TITLE
How the High and low band gets calculated for sudden change at detector level.

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1639]
We are trying to figure out how we can apply the sudden change in the detector alert setting. Based on the current and historical time window the high and low bands are getting varied. But not sure on what basis it is getting calculated.

**Comment by dloucasfx** [comment]
@RPooja08 
This is not a smart agent specific question and more related to detectors and core functionalities.
Please open a support case to get the appropriate resources to provide the right assistance.

**Comment by RPooja08** [comment]
Thanks, @dloucasfx for the guidance.
