### ISSUE TITLE
custom metric is not getting send to signalfx via exec plugin.

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1640]
We are using the exec plugin to execute the script and get the output via custom metric in SignalFx. But the custom metric is not getting populated. Please assist with this.

Below is the YAML file, script, and error log.

Error: time="2021-03-18T02:50:35-04:00" level=info msg="exec plugin: Program `/etc/signalfx/db_availability.sh' has closed STDERR." collectdInstance=monitor-11

YAML Config:

  - type: collectd/custom
    template: |
      LoadPlugin exec
      <Plugin exec>
        Exec "signalfx-agent" "/etc/signalfx/db_availability.sh"
      </Plugin>

Script:

#!/bin/bash

export ORACLE_BASE=BASEPATH
export ORACLE_HOME=HOMEPATH
export PATH=$ORACLE_HOME/bin:$PATH
export ORACLE_SID=S_ID

FILE=/etc/signalfx/sqlfile.sql
INTERVAL="${COLLECTD_INTERVAL:-60}"
HOSTNAME="${COLLECTD_HOSTNAME:-localhost}"

DB="$(timeout 15 sqlplus -S User/Pass@SID @/etc/signalfx/sqlfile.sql | awk '{print $1}')"
DBCol=$(timeout 15 sqlplus -S User/Pass@SID @/etc/signalfx/sqlfile.sql | awk '{print $2 " " $3}')
OpenMode="READ WRITE"

if [ "$OpenMode" == "$DBCol" ]
then
VALUE=1
echo "PUTVAL \"HOSTNAME-demo/exec-$DB/gauge-openmode\" interval=$INTERVAL N:$VALUE"
fi

**Comment by keitwb** [comment]
Are you sure that `$OpenMode == $DBCol`?  If not, then nothing would be emitted.

**Comment by RPooja08** [comment]
yes, then there will not be any data. So I will be using a heartbeat. but the custom metric is not getting emit I tried in the dev server and it worked fine not sure why it is not working in prod.

**Comment by keitwb** [comment]
If it works fine in dev but not prod that means there is probably something wrong with the logic in the script, possibly the credentials, or the values you are gettting back from the sqlplus commands.  I would print messages to stderr to help debug.

**Comment by RPooja08** [comment]
we have created the complete replica in prod from dev, the credentials used for DB connection is same and with the same set of privileges, the script is also same only environment variables are changed based on the environment path. Manually when I ran the script, it is giving the correct output.

**Comment by RPooja08** [comment]
I was able to resolve the issue after giving read permission to tnsname.ora and listner.ora file.
