### ISSUE TITLE
Agent Telemetry - SignalFX-Agent

### ISSUE THREAD

**Issue by Forcebyte** [signalfx/signalfx-agent#1645]
Hi there!

## Background

We are attempting to use the SignalFX agent as an individual sender to Splunk for metrics on Windows Kubernetes Nodes as recommended to us by Pro-Serve; ideally we do not want to attempt to forward events to SignalFX by default

Today, there exists a splunk schema here (https://docs.signalfx.com/en/latest/integrations/agent/config-schema.html#splunk) which defines logging to a Splunk instance which we are using

## Issue

From first pass the assumption here is that there is a method to disable forwarding to the SignalFX agent, however it appears that without a direct connection to SignalFX the agent attempts to attempt to signalFX multiple times per milisecond; our firewall software has caught the following
```
 HTTPS request from xxx:18529 to api.xx.signalfx.com:443. Action: Deny. No rule matched. Proceeding with default action 
```

This occurs with urls `ingest.xx.signalfx.com` and `api.xx.signalfx.com`

This also happens very frequently, which degrades performance of our firewall instances, with timestamps going within the milisecond
```
3/24/21 9:45:37.761 AM
3/24/21 9:45:37.760 AM
3/24/21 9:45:37.192 AM
```

## Questions

I was wondering if
- There was a way to disable forwarding of the SignalFX agent to SignalFX itself so the agent would stop 'phoning home' (It sounds like an odd request, but above is an example usecase, where we want to limit the amount of unnecessary traffic within our environment
- If there was any default diagnostic data that signalFX attempts to send, and if there was a way to disable that?

**Comment by keitwb** [comment]
Try setting

```
writer:
  signalfxEnabled: false
```

in your config.  I think that will mostly do what you want.

Without seeing your full config I don't know what it might be trying to send or not.

**Comment by Forcebyte** [comment]
ah crud; thats in the config site too and I missed it!

Thank you @keitwb! Going to try that, closing issue
