### ISSUE TITLE
agent version 5.9.2 fails to start without whitelist.json but starts with empty whitelist.json without any issue

### ISSUE THREAD

**Issue by banlex73** [signalfx/signalfx-agent#1717]
From the log file
Apr 13 00:01:19 postgres-tst-uscentral1-naauditstore1-0 systemd: signalfx-agent.service: main process exited, code=exited, status=1/FAILURE
Apr 13 00:01:19 postgres-tst-uscentral1-naauditstore1-0 systemd: Unit signalfx-agent.service entered failed state.
Apr 13 00:01:19 postgres-tst-uscentral1-naauditstore1-0 systemd: signalfx-agent.service failed.
Apr 13 00:01:20 postgres-tst-uscentral1-naauditstore1-0 systemd: signalfx-agent.service holdoff time over, scheduling restart.
Apr 13 00:01:20 postgres-tst-uscentral1-naauditstore1-0 systemd: Stopped SignalFx Agent.
Apr 13 00:01:20 postgres-tst-uscentral1-naauditstore1-0 systemd: Started SignalFx Agent.
Apr 13 00:01:20 postgres-tst-uscentral1-naauditstore1-0 signalfx-agent: time="2021-04-13T00:01:20Z" level=info msg="Starting up agent version 5.9.2"
Apr 13 00:01:20 postgres-tst-uscentral1-naauditstore1-0 signalfx-agent: time="2021-04-13T00:01:20Z" level=info msg="Watching for config file changes"
Apr 13 00:01:20 postgres-tst-uscentral1-naauditstore1-0 signalfx-agent: time="2021-04-13T00:01:20Z" level=error msg="Error loading main config" configPath="/etc/signalfx/agent.yaml" error="could not resolve path file:/usr/lib/signalfx-agent/lib/whitelist.json: file(s) not found"

**Comment by keitwb** [comment]
Hi, this is due to the config file referencing the whitelist.json file.  Grep for it in your agent.yaml and remove any references to it.

**Comment by banlex73** [comment]
thank you for explanation. 
I fixed it creating an empty **whitelist.json**
