### ISSUE TITLE
reading k8s project annotations --> add as Dimension or Property

### ISSUE THREAD

**Issue by AchimGrolimund** [signalfx/signalfx-agent#1719]
Hey all

is it possible to read the annotations from a `kind: Project` through the signalfx agent and add it as dimension?

Her an example yaml file

```yaml
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: ch-myapp
  selfLink: /apis/project.openshift.io/v1/projects/ch-myapp
  uid: 81a99414-xxxx-4b20-xxxx-c766ab41a481
  resourceVersion: '201078305'
  creationTimestamp: '2021-02-10T10:04:14Z'
  labels:
    name: ch-myapp
    policy-twilio: ch-myapp
  annotations:
    mycompany.io/application-id: 4a802e88
    openshift.io/description: ''
```

i would set the `mycompany.io/application-id` as Dimension like `Leanix_id: 4a802e88` to every POD inside this Project.

we use CRI-O and Openshift 4.6+ and the newest SignalFX-Agent

Thanks for Helping

greetings

**Comment by keitwb** [comment]
Hi @EvilAcid, doing this with the agent config directly is not possible.  You can read the annotations on specific pods with the `extraDimensionsFromEndpoint` config on the monitors that have discovery rules that make use of endpoints from the `k8s-api` observer.  But reading values from an arbitrary resource like `Project` and adding them as dimensions is not currently a feature.

If the `kubernetes-cluster` monitor sent in Project metrics and added a property with the annotation to the Project UID dimension we could then have the pods include that Project UID dimension and you would get the annotation property applied to the pods as well, but that is a substantial enhancement and the Smart Agent is currently being transitioned to the [OpenTelemetry Collector](https://github.com/signalfx/splunk-otel-collector) so we are trying not to add anything new to the Smart Agent.  The Collector is certain open to such things though.

In the short term though, my recommendation would be to write a little script that is run as a CronJob in OpenShift that gets the Pods under a Project and syncs the annotation you want as a property on the `kubernetes_pod_uid` dimension that the `kubernetes-cluster` montior uses to identify each pod.  This will give you access to the annotation in charts and detectors.  It would look something like this in pseudocode:

```
for each Project:
  app_id = project.annotations["mycompany.io/application-id"]
  for each Pod in this Project:
     pod_json = http.GET_json("https://api.<realm>.signalfx.com/v2/dimension/kubernetes_pod_uid/<Pod.UID>")
     pod_json.customProperties["Leanix_Id"] = app_id
     http.PUT("https://api.<realm>.signalfx.com/v2/dimension/kubernetes_pod_uid/<Pod.UID>", data=pod_json)
```

There are some edge cases not covered like if the dimension doesn't exist yet, but that is the general idea of what you want.  We do this kind of thing internally for monitoring our own backend as it is infinitely flexible and allows for a lot of things not really feasible for a generic agent to do.

Let me know if that helps.
