### ISSUE TITLE
Is Siganlfx is supported on SUSE Linux 11?

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1757]
We are getting errors while installing an agent on SUSE Linux 11 and unable to install the agent. please suggest the same.
![image](https://user-images.githubusercontent.com/68017992/117325143-16809480-aeae-11eb-9cb1-a19d5446b714.png)

**Comment by jcheng-splunk** [comment]
@RPooja08 I believe that openssl 1.0.1g is required to support TLS v1.2 for gpg verification of our rpm packages and repo.  Alternatively, you can try using the standalone bundle: https://github.com/signalfx/signalfx-agent/blob/main/docs/agent-install-standalone-linux.md.

**Comment by RPooja08** [comment]
@jcheng-splunk I have tried installing as per the link but received the below error while installing.
![image](https://user-images.githubusercontent.com/68017992/117433923-aaec0500-af49-11eb-8176-04b82e25aee6.png)

**Comment by RPooja08** [comment]
We have fixed the memory issue but installation is getting stuck for hours and not getting installed. Please suggest the same.
![image](https://user-images.githubusercontent.com/68017992/117457480-e2b57580-af66-11eb-82b7-b36795773814.png)

**Comment by RPooja08** [comment]
@jcheng-splunk I have checked in the backend but SignalFx services were not running. also, check on the SignalFx console there also it wasn't listing.
After running the command for so long, when we abort that till the time also it is not getting installed.
