### ISSUE TITLE
Is collectd plugin is supported in SUSE 11 OS.

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1770]
Is collectd plugin is supported in SUSE 11 OS.

We have manually installed the agent on suse 11 OS. Agent is running fine but unable to do the service monitoring via collectd plugin.

![image](https://user-images.githubusercontent.com/68017992/118646864-5d4f8200-b7fe-11eb-947f-de7fe2b1bad7.png)

**Comment by keitwb** [comment]
Did you run `bin/patch-interpreter $(pwd)` from inside the `signalfx-agent` directory?  See the instructions at https://github.com/signalfx/signalfx-agent#linux-standalone-targz.

**Comment by RPooja08** [comment]
Yes to install manually agent on SUSE 11 I ran this command. Is there any way with which collectd can be used?
Please assist.

**Comment by keitwb** [comment]
What happens if you run `/home/ec2-user/signalfx-agent/bin/collectd` from the command line?

**Comment by RPooja08** [comment]
I get below output:

![image](https://user-images.githubusercontent.com/68017992/118674834-baa3fd00-b817-11eb-89a0-c5bbc18a0dd9.png)

**Comment by keitwb** [comment]
Show me the output of `bin/patch-interpreter $(pwd)` in the `signalfx-agent` directory.  That part might have failed.

**Comment by RPooja08** [comment]
Here is the requested output:

![image](https://user-images.githubusercontent.com/68017992/118777042-45cbd400-b8a6-11eb-9577-8561bcf65e8d.png)

**Comment by keitwb** [comment]
Try running collectd again and if it still doesn't work show me the output of `ldd /home/ec2-user/signalfx-agent/bin/collectd`.

**Comment by RPooja08** [comment]
It is still not working, please find below snip:

![image](https://user-images.githubusercontent.com/68017992/118848790-b3025800-b8ec-11eb-8544-86fde6718d7f.png)

**Comment by keitwb** [comment]
How are you starting the agent?

**Comment by RPooja08** [comment]
service signalfx-agent start

**Comment by keitwb** [comment]
ok, I suspect SUSE 11 is too old to run collectd as it was released almost 12 years ago now.  Mainly because it still uses kernel 2.6.  Best thing to do is to just disable collectd and use the newer Go monitors -- they have a better chance of working on old kernels.

**Comment by RPooja08** [comment]
but for suse 11 it shows kernal version 3.x.x

**Comment by keitwb** [comment]
ok, there might be some other reason due to the age of the distro.  When you get that error even when the file exists it is usually an indication that something is incompatible with the kernel.

**Comment by RPooja08** [comment]
then we don't have any other option to use collectd plugin.
