### ISSUE TITLE
Add comment around resources & memory usage

### ISSUE THREAD

**Issue by narmendariz** [signalfx/signalfx-agent#1774]
Under resources:
https://github.com/signalfx/signalfx-agent/blob/main/deployments/k8s/helm/signalfx-agent/values.yaml#L85

These limits are an example that, if used, are likely too low and will cause oom crashes.
We should add a comment to recommend customers adjust these as necessary given the load applied by the amount of monitors they are using.

**Comment by clayvan** [comment]
Out of curiosity, what sort of usage are you seeing?

I'm currently seeing my pods consuming around 60-70mb of a memory, but occasionally one will spike to 1-3GB of usage and get OOMkilled.

I'm currently investigating if this is a memory leak, or expected usage (can't possibly be), or something else.

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
