### ISSUE TITLE
Signalfx agent utilized all the TCP connections.

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1781]
We are monitoring the query-based MSSQL database.  Where we found that the SignalFx agent has occupied all the TCP connections.

**Comment by keitwb** [comment]
Can you provide your config and which agent version you are using?

**Comment by RPooja08** [comment]
Below is the yaml Configuration:

---
# *Required* The access token for the org that you wish to send metrics to.
signalFxAccessToken: tokennumber
ingestUrl: {"#from": '\ProgramData\SignalFxAgent\ingest_url', default: "A"}
apiUrl: {"#from": '\ProgramData\SignalFxAgent\api_url', default: "B"}

intervalSeconds: 10

logging:
  # Valid values are 'debug', 'info', 'warning', and 'error'
  level: info

# observers are what discover running services in the environment
observers:
  - type: host

monitors:
  - {"#from": '\ProgramData\SignalFxAgent\monitors\*.yaml', flatten: true, optional: true}
  - type: host-metadata
  - type: processlist
  - type: cpu
  - type: disk-io
  - type: filesystems
  - type: memory
  - type: net-io
  - type: vmem
  - type: telegraf/win_perf_counters
    printValid: true
    objects:
     - objectName: "System"
       instances:
        - "*"
       counters:
        - "System Up Time"
       includeTotal: true
       measurement: "win_Uptime"

  - type: telegraf/sqlserver
 
    host: localhost
    port: portno

    userID: username
    password: Password
    appName: SFA
    extraMetrics:
      - sqlserver_server_properties.db_offline
      - sqlserver_performance.number_of_deadlocks_sec
      - sqlserver_performance.processes_blocked
      - sqlserver_server_properties.db_online
      - sqlserver_server_properties.db_restoring
      - sqlserver_server_properties.db_recovering
      - sqlserver_server_properties.db_suspect

  - type: telegraf/win_services

    serviceNames:
      - A
      - B

  - type: sql
    host: localhost:portno
    port: portno
    dbDriver: sqlserver
    params:
      user: signalfxagent
      password: Password

    connectionString: 'sqlserver://user:Password@localhost:portno'
    queries:

      - query: "DB query'"
        metrics:
          - metricName: "DBLongQuery"
            valueColumn: "count"

  - type: sql
    host: localhost:portno
    port: portno
    dbDriver: sqlserver
    params:
      user: user
      password: Password

    connectionString: 'sqlserver://user:Password@localhost:portno'
    queries:

      - query: "DB Query"
        metrics:
          - metricName: "DBJobFail"
            valueColumn: "Job_count"
            dimensionColumns: ["A", "B", "C", "D"]

##############################################

Agent Version: 5.4.0
