### ISSUE TITLE
how to check otel-contrib-collector.service if we have installed it in manually 

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1782]
how to check otel-contrib-collector.service if we have installed it in manually

**Comment by jcheng-splunk** [comment]
@RPooja08 Are you referring to the https://github.com/open-telemetry/opentelemetry-collector-contrib project?  If so and you installed the deb or rpm from https://github.com/open-telemetry/opentelemetry-collector-contrib/releases, you can run `sudo systemctl status otel-contrib-collector` to check the service status, and `sudo journalctl -u otel-contrib-collector` for logs.

Also, please post any issues related to otel-contrib-collector to that project instead.

**Comment by RPooja08** [comment]
Thank you @jcheng-splunk for the details.
