### ISSUE TITLE
How telegraf/sqlserver plugin fetch the sql metrics.

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1783]
How telegraf/sqlserver plugin fetches the SQL metrics. We want to know how this plugin fetches the DB data. We are facing the issue where we are getting the data for DB offline metric, not for other metrics.

**Comment by AchimGrolimund** [comment]
Hey @RPooja08 
if you search the Source of this Monitor, here is it: 

https://github.com/signalfx/signalfx-agent/blob/main/pkg/monitors/telegraf/monitors/mssqlserver/mssqlserver.go

Greetings Achim

**Comment by RPooja08** [comment]
Thanks, @AchimGrolimund.
