### ISSUE TITLE
what config and where to add to start monitoring services from otel agent.

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1789]
We are trying to add the windows services config in yaml file for otel agent. But looks like I am not adding correct config code to yaml file.  Please suggest the same.

**Comment by RPooja08** [comment]
I added as below:

receivers:
  signalfx:
    smartagent/memory:
      type: telegraf/memory
    smartagent/win_services:
      type: telegraf/win_services
      serviceNames:
        - Spooler

**Comment by mstumpfx** [comment]
Hi @RPooja08  - for any questions related to Splunk Otel Collector, I would advise you to open the issues in that repository:  https://github.com/signalfx/splunk-otel-collector

This way we will get the right eyes on the issue. Thanks!

**Comment by RPooja08** [comment]
Thank you for the clarification.. I will post on the mentioned forum. 👍
