### ISSUE TITLE
how to get the sfx metric details and its complete description.

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1856]
Is there any way to get all the details regarding the metric "sfx.org.num*" .

**Comment by rmfitzpatrick** [comment]
@RPooja08, is https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.signalfx.organization.metrics.html#metrics what you're referring to and adequate?

**Comment by rpille-sfx** [comment]
Better to use the new O11y site: this is the one we update now. https://docs.splunk.com/Observability/admin/org-metrics.html#nav-Usage-metrics-for-Splunk-Observability-Cloud

**Comment by RPooja08** [comment]
Thank you so much... this document is really helpful.
