### ISSUE TITLE
SignalFx agent installation on proxy based server

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#1863]
We are having so many servers where the proxy is enabled. All the traffic is traversing via proxy to the internet. We have installed the SignalFx agent and before installation enabled the proxy configuration as per doc "https://docs.splunk.com/Observability/gdi/smart-agent/smart-agent-resources.html#use-proxy-support" but still agent is unable to send the data to SignalFx console.

Kindly suggest on this.
OS: RHEL 7.6
SFX agent: 5.9.2

**Comment by RPooja08** [comment]
Do we have any suggestions on this issue?

**Comment by rmfitzpatrick** [comment]
Hi @RPooja08 I think we'd need a bit more information about your environment and the problematic behavior to be of assistance for this issue.  If you're using a standard proxy the values of the proxy env vars and the existence of `NO_PROXY` would be helpful.  Confirmation that the proxy is functional from the hosts in question using `curl --proxy` (or proxy env vars) would be a good sanity test.  Also more details on what "unable to send the data to SignalFx console" means and what you are experiencing would be appreciated.

For general support issues with the Smart Agent and Splunk IM/SignalFx as a customer, I'd suggest reaching out to observability-support@splunk.com directly.  We're happy to help here as we can but you should have a better experience working with a representative and they can reach out to engineering if something is off on our end.

**Comment by RPooja08** [comment]
Hi @rmfitzpatrick  yes proxy is enabled, below is the output:

[root@ip-10-0-64-138 signalfx-agent.service.d]# env | grep -i proxy
http_proxy=http://ec2-18-116-65-161.us-east-2.compute.amazonaws.com:3128
https_proxy=https://ec2-18-116-65-161.us-east-2.compute.amazonaws.com:3128

Please suggest how we can procced next
