### ISSUE TITLE
Error: " Unable to collect username for process " from SignalFx agent

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#2021]
We are running SignalFx agent on Windows OS. Most of the time we are getting below error multiple time in events log.

msg="Unable to collect username for process {System Idle Process 0xc000d84930 0xc000d84950 2021-11-21 02:12:33.670358 +0000 GMT 0 0 0xc000d84980 0xc000d18870 247648664531250 0 0 4096 65536}. unable to open process handle. The parameter is incorrect." monitorType=processlist 

Is this error usual or it will cause any issue to OS platform like increase handle counts or other OS ressource.

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
