### ISSUE TITLE
API to get the list of CI reporting to console from any cloud native like EC2 instances

### ISSUE THREAD

**Issue by RPooja08** [signalfx/signalfx-agent#2115]
I am trying to fetch the server details via API. I am using the below API to get the active server list but in the infrastructure tab the count is pretty real-time and via API I am getting active data for 25 hours. Any suggestion for the API which I can use to get the real-time active data as getting from the Infrastructure tab.

https://api.us1.signalfx.com/v2/metrictimeseries?query=sf_metric:CPUUtilization AND sf_key:InstanceId AND _exists_:InstanceId AND stat:mean AND sf_isActive:true &limit=9999

**Comment by atoulme** [comment]
This is not related to the agent itself but to the API. Please consider opening a support request to receive assistance.
