### ISSUE TITLE
logLevel is not working in signalfx helm chart

### ISSUE THREAD

**Issue by venkatnpedada** [signalfx/signalfx-agent#2118]
logLevel is not working in signalfx helm chart. We are using same value for both agent logging and collectd logging, but both expect different inputs to change the logging.

agent logging logLevel values :-    Valid values are 'debug', 'info', 'warn', and  'error'. 
collectd logging logLevel values :-  valid choices are [debug, info, notice, warning, err]"

https://github.com/signalfx/signalfx-agent/blob/main/deployments/k8s/helm/signalfx-agent/templates/configmap.yaml#L83
https://github.com/signalfx/signalfx-agent/blob/main/deployments/k8s/helm/signalfx-agent/templates/configmap.yaml#L277

When I tried to use same value 'error' property in the helm, Observing below error while starting the signalfx container

```
time="2022-02-28T08:54:56Z" level=info msg="Starting up agent version 5.16.0"
time="2022-02-28T08:54:56Z" level=info msg="Watching for config file changes"
time="2022-02-28T08:54:56Z" level=error msg="Error loading main config" configPath="/etc/signalfx/agent.yaml" error="configuration is invalid: invalid collectd log level error, valid choices are [debug, info, notice, warning, err]"
```

**Comment by atoulme** [comment]
Thank you for your report. The SignalFx agent is deprecated and we recommend you use the OpenTelemetry Collector instead.
Please prefer the Splunk distribution of the OpenTelemetry chart:
https://github.com/signalfx/splunk-otel-collector-chart

T
