### ISSUE TITLE
Agent Occasionally Drops HTTP POST Connections

### ISSUE THREAD

**Issue by jcburley** [signalfx/signalfx-agent#2140]
We're seeing a fair number of these errors occasionally among our microservices (running on K8S, AWS, etc):

```
Feb 24 21:07:07 <whatever> 2022/02/25 02:07:07 notifying bugsnag: failed to flush Jaeger spans to server: Post "http://ip-10-NNN-NNN-NNN.ec2.internal:9080/v1/trace": EOF
```

As there are a number of "moving parts" here, it's been difficult to track down just what's happening.

It looks like `signalfx-agent` is sometimes having trouble pushing traces up further, e.g.:

```
Feb 24 23:03:58 signalfx-agent-XXX signalfx-agent error time="2022-02-25T04:03:58Z" level=error msg="Could not get prometheus metrics" error="prometheus exporter at http://10.NNN.NNN.NNN:9102/metrics returned status 503: upstream connect error or disconnect/reset before headers. reset reason: connection failure" 
```

It's not clear this issues are related, but we can't rule that out. (I find "Could not get..." confusing, as it suggests an attempt to retrieve, rather than write, traces; so I'm not sure this is in any way related, or that I'm even looking at the right component or logs.)

Is it possible `signalfx-agent` is dropping HTTP POST connections, rather than returning HTTP result codes indicating errors, in certain cases, resulting in the POST clients getting EOF's while writing data to the TCP connection? (I'm not aware of other potential causes of EOF in such cases.)

And, what, if any, guidance can you offer here? As this technology stack is deprecated in favor of OpenTelemetry, should we move to that (which I think might be fairly heavy lifting at this point), or would that not solve problems like this?

Thanks!

**Comment by atoulme** [comment]
Please consider moving to OpenTelemetry. Closing this issue as inactive. Please reopen if needed.
