### ISSUE TITLE
Helm chart version 1.9.4 does not work with App version 5.21.0 (error retrieving resource lock during leaderelection)

### ISSUE THREAD

**Issue by davy-oo** [signalfx/signalfx-agent#2295]
The latest chart version that was released was 1.9.4 for app version 5.16.0 in repository "https://dl.signalfx.com/helm-repo".

This https://github.com/signalfx/signalfx-agent/pull/2216 PR seems to have introduced a breaking change which would require a new helm chart to avoid messages like following when helm is used to deploy agent 5.21.0 on K8s:
_E0629 14:47:07.257529       1 leaderelection.go:330] error retrieving resource lock signalfx/signalfx-agent-leader: leases.coordination.k8s.io "signalfx-agent-leader" is forbidden: User "system:serviceaccount:signalfx:signalfx-agent" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "signalfx"_

The message appears every minute.

Would it be possible to have a new helm chart released which would work for 5.21.0? This would be useful to install security updates before to move away to a non deprecated agent.

**Comment by jeffreyc-splunk** [comment]
Thanks @davy-oo and apologies for the oversight.  We released version 1.10.0 of the helm chart with the updated clusterrole.  Please let us know if it resolves the issue for you.

**Comment by davy-oo** [comment]
All good now, thanks for quick fix. Somehow a PR merge with a reference to this issue in a private repository closed this automatically.
