### ISSUE TITLE
What is the upcoming release schedule?

### ISSUE THREAD

**Issue by alex-rowe** [signalfx/signalfx-agent#2355]
With the repository being deprecated in December, how often will new releases be made available?

There are some security fixes in `main` that aren't in a release yet which we'd like to use.

**Comment by aunshc** [comment]
While the Smart Agent is already deprecated and will reach End of Support in December this year, up to that point, we plan to release the Agent as soon as any critical security updates or bug fixes that need to make it. Can you confirm that the latest release https://github.com/signalfx/signalfx-agent/releases/tag/v5.22.0 includes the fixes that you would like to use?

**Comment by alex-rowe** [comment]
Yes that fine, 5.22 includes the fixes we were after.
