### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by JonnyBGod** [signalfx/signalfx-agent#246]
Using rancher 2.0.0-beta2

```
time="2018-04-12T18:29:51Z" level=info msg="Initialization complete, entering read-loop." collectdInstance=global
time="2018-04-12T18:29:51Z" level=info msg="found host migration-dev1" collectdInstance=global plugin=signalfx-metadata
time="2018-04-12T18:29:56Z" level=info msg="adding small dither of 19 seconds before sending notifications" collectdInstance=global plugin=signalfx-metadata
time="2018-04-12T18:29:57Z" level=error msg="Couldn't get machine info: Get https://migration-dev1:10250/spec/: x509: certificate signed by unknown authority"
time="2018-04-12T18:29:57Z" level=error msg="Couldn't get cAdvisor container stats" error="failed to get all container stats from Kubelet URL "https://migration-dev1:10250/stats/container/": Post https://migration-dev1:10250/stats/container/: x509: certificate signed by unknown authority"
time="2018-04-12T18:30:02Z" level=error msg="Could not fetch docker stats for container id 44efdc1bd4ebcc3d5a2e14a489347f3bef04c59fe9f0c478fe35fd9982373d54" error="context deadline exceeded" monitorType=docker-container-stats
time="2018-04-12T18:30:02Z" level=error msg="Could not fetch docker stats for container id bf1f1dbf94a80467369d48608f896d765a090de2a657232410d0c02249382647" error="context deadline exceeded" monitorType=docker-container-stats
time="2018-04-12T18:30:02Z" level=error msg="Could not fetch docker stats for container id e478525a3f08f917937bb8d251c41534fe59f083637d7257ef0622541d50cd0e" error="context deadline exceeded" monitorType=docker-container-stats
time="2018-04-12T18:30:02Z" level=error msg="Could not fetch docker stats for container id 0253ac7cf61a0106f3a9176df857ef6cb03a8da19b866d42354b3abea8222361" error="context deadline exceeded" monitorType=docker-container-stats
```

**Comment by keitwb** [comment]
Try this config for the `kubelet-stats` monitor:

```
monitors:
  - type: kubelet-stats
    kubeletAPI:
      skipVerify: true
  ...
```

For more information, see https://github.com/signalfx/signalfx-agent/blob/master/docs/monitors/kubelet-stats.md.  Heapster (the analogue of kubelet-stats when using prometheus) defaults to not verifying the kubelet cert but we have left verification on by default.  Since the host filesystem is mounted into the agent container at `/hostfs` you can also use the `caCertPath` option under `kubeletAPI` and specify that if you know where the CA cert is on the node's filesystem (assuming that the simple hostname of the node matches the cert's common name.

**Comment by ramyala** [comment]
I've tried the `skipVerify: true` but ended up with the following error. Currently I'm seeing signalfx-agent spewing on the log console every 20-60s with the same set of messages. Could this be related to GKE specifically?

```
time="2018-06-12T21:29:37Z" level=error msg="Couldn't get machine info: Kubelet request failed - "401 Unauthorized", response: "Unauthorized""
time="2018-06-12T21:29:37Z" level=error msg="Couldn't get cAdvisor container stats" error="failed to get all container stats from Kubelet URL "https://gke-cluster-default-pool-e7ffd064-xd60:10250/stats/container/": Kubelet request failed - "401 Unauthorized", response: "Unauthorized""
```

**Comment by keitwb** [comment]
Yes, GKE does not provide a way to authenticate from pods to the standard kubelet endpoint on port 10250.  _However_, they do provide an alternate endpoint on port 10255 that allows you to do a small subset of read-only operations against the kubelet.  See https://github.com/signalfx/signalfx-agent/blob/master/docs/kubernetes-setup.md#google-container-engine-gke.

**Comment by ramyala** [comment]
@keitwb There is a discrepancy in documentation for the signalfx helm chart and authType default for kubelet-plugin. Can you clarify in the documentation to specify authType: none alongside the url for GKE.

**Comment by keitwb** [comment]
@ramyala Hopefully https://github.com/signalfx/signalfx-agent/pull/336 will clarify that a bit.  Even if somebody did leave in the serviceAccount auth it should still work, although it would not be ideal from a security standpoint to send credentials over HTTP.
