### ISSUE TITLE
Monitor never create with discoveryRule

### ISSUE THREAD

**Issue by GodfreyLyu** [signalfx/signalfx-agent#2484]
Hi,

Environment: Openshift Kubernetes Cluster 
Signalfx Agent Image Tag: 5.10

I am currently configuring a monitor to watch my cadviosr pod metrics 
My cadvisor pod is managed by a daemonset and exporting metrics through pod Ip and port number 8080. The namespace cadvisor using is **cadvisor**. 

I tried both **proemetheus-exporter** type and **cadvisor** type, but seems like my below discoveryRule is never functioning while the agent starts. 

 - type: prometheus-exporter
    discoveryRule: 'target == "pod" && namespace == "cadvisor" && discoverAllPods == true && port == 8080'
    extraDimensions:
      metric_source: my_monitor
    validateDiscoveryRule: true

Can you please kindly review the configuration and let me know?

Thanks in advance!
Godfrey

**Comment by atoulme** [comment]
Hello Godfrey,
Would you be open to try to use the OpenTelemetry Collector instead?
Here is an example, which admittedly is not as complex as your use case:
https://github.com/signalfx/splunk-otel-collector/blob/main/examples/splunk-hec-prometheus/otel-collector-config.yml#L8

**Comment by GodfreyLyu** [comment]
Thank you for the quick reply! 
In our usecase, we would like to manage/publish all metrics through signalfx-agent.
Is there any way we could detect a monitor endpoint in pod level?
I've set the logLevel as debug, but still not much information I could retrieve 

> Hello Godfrey, Would you be open to try to use the OpenTelemetry Collector instead? Here is an example, which admittedly is not as complex as your use case: https://github.com/signalfx/splunk-otel-collector/blob/main/examples/splunk-hec-prometheus/otel-collector-config.yml#L8
