### ISSUE TITLE
Bump issue in k8s deployment files

### ISSUE THREAD

**Issue by dje4om** [signalfx/signalfx-agent#2591]
Hi,

There is an error in the bump commit in k8s daemonset file, `5.24.0` instead of `5.26.0`

https://github.com/signalfx/signalfx-agent/pull/2582/commits/5db7e8064877d0a4cd1b8bd9090464a118367a49#diff-5916eda2aa505ca2db2a4719550d52b52ed6832385171d5978c21a62b21a6023

**Comment by atoulme** [comment]
This is now fixed. Thank you for your report!
