### ISSUE TITLE
check_links action should ignore SQL link

### ISSUE THREAD

**Issue by crobert-1** [signalfx/signalfx-agent#2663]
The `check_links` action is currently failing due to what it detects to be a broken link. The link is valid and working though, and has been in the document for a couple of years at this point, so it's a test failure.

Failing action: https://github.com/signalfx/signalfx-agent/actions/runs/3833349091/jobs/6525260979
Failing line: https://github.com/signalfx/signalfx-agent/blame/main/docs/monitors/sql.md#L82
Failling link: https://dev.mysql.com/doc/refman/8.0/en/show-slave-status.html

There may be a way to get the same link to work successfully, otherwise we should just have `check_links` ignore it.

**Comment by atoulme** [comment]
I think the link needs to be updated to https://dev.mysql.com/doc/refman/8.0/en/show-replica-status.html.

**Comment by crobert-1** [comment]
Good catch, thanks!
