### ISSUE TITLE
Redis ListLength expects DBIndex/KeyPattern dict but redis_info.py expects tuple

### ISSUE THREAD

**Issue by joshma** [signalfx/signalfx-agent#521]
The `ListLength` struct (https://github.com/signalfx/signalfx-agent/blob/master/internal/monitors/collectd/redis/redis.go#L59) has keys `DBIndex` and `KeyPattern`.

However, `redis_info.py` (https://github.com/signalfx/redis-collectd-plugin/blob/master/redis_info.py#L245) expects a 2-item list (`(len(node.values)) == 2`). This causes the integration to break - you get a warning "redis_info plugin: monitoring length of keys requires both database index and key value".

If I had to guess, the fix could be to modify https://github.com/signalfx/signalfx-agent/blob/master/internal/monitors/collectd/redis/redis.go#L115 to just convert `conf.SendListLengths` into this tuple form.

**Comment by keitwb** [comment]
Thanks for reporting this @joshma.  I made a fix for it and added an integration test for the functionality.  I'll do a patch release later today if all goes well in CI.

**Comment by keitwb** [comment]
Ok, this is released in 3.9.5

**Comment by joshma** [comment]
Thanks @keitwb ! Will try to test this today / tomorrow.
