### ISSUE TITLE
Windows service can not be restarted via chef

### ISSUE THREAD

**Issue by mitom** [signalfx/signalfx-agent#713]
With the introduction of python monitors it has become necessary to restart the agent once the monitors change, as the changes are not detected otherwise. Currently this does not seem possible due to the guards in the windows service resource. The effect is, that even thought chef schedules the restart of the service, the resource decides there is nothing to be done due the agent version matching what's expected. In other words, it's only possible to restart the service via chef when the version changes:

So doing something like the following in a recipe
```
  cookbook_file "#{integration_directory}\\bitlocker.py" do
    source 'integrations/bitlocker.py'
    action :create
    notifies :restart, "windows_service[#{node['signalfx_agent']['service_name']}]", :delayed
  end
```
would yield:
```
[2019-04-15T14:14:33+00:00] INFO: cookbook_file[\Program Files\SignalFx\\integrations\bitlocker.py] sending restart acti
on to windows_service[signalfx-agent] (delayed)
Recipe: signalfx_agent::win
  * windows_service[signalfx-agent] action restart[2019-04-15T14:14:33+00:00] INFO: Processing windows_service[signalfx-
agent] action restart (signalfx_agent::win line 1)
 (skipped due to only_if)
[2019-04-15T14:14:33+00:00] INFO: Chef Run complete in 10.9068 seconds
```

(note the `skipped due to only_if` above)

Could you please either fix the agent so it detects changes to the custom python integrations without a restart, or the chef cookbooks so that the restart can be triggered on the service?

**Comment by keitwb** [comment]
I think in general the better approach is to have your surrounding Chef recipes invoke the service restart after setting the Python scripts in place, but it isn't clear to me how to allow the notification to go through without being skipped and still not stop the service every time you run Chef (which would be highly undesirable in general).

The only thing I can think of to accomplish that is for your own Chef recipies to have something like:

```
windows_service my_name do
  action :nothing
  service_name node['signalfx_agent']['service_name']
end

cookbook_file ... do
  ...
  notifies :restart, "windows_service[my_name]", :delayed
end

Where you just make a distinct resource name pointing to the same service.

You could also try invoking a restart on the plain `service[#{node['signalfx_agent']['service_name']}"` resource that gets used even on windows.

Let me know if either of those two things helps.

**Comment by mitom** [comment]
The first suggestion seems pretty dirty, it will result in multiple restarts of the service for each definition.

I gave the 2nd one a try, it does work although it seems like more of a bug in chef than anything else. It still refers to it as `windows_service` and still detects that it's defined, but it ignores the guards around it.

```
  cookbook_file "#{integration_directory}\\bitlocker.py" do
    source 'integrations/bitlocker.py'
    action :create
    notifies :restart, "service[#{node['signalfx_agent']['service_name']}]", :delayed
  end
```
```
[2019-04-16T13:37:52+00:00] INFO: cookbook_file[\Program Files\SignalFx\\integrations\bitlocker.py] sending restart acti
on to windows_service[signalfx-agent] (delayed)
Recipe: signalfx_agent::default
  * windows_service[signalfx-agent] action restart[2019-04-16T13:37:52+00:00] INFO: Processing windows_service[signalfx-
agent] action restart (signalfx_agent::default line 56)
[2019-04-16T13:37:54+00:00] INFO: windows_service[signalfx-agent] configured.
[2019-04-16T13:37:57+00:00] INFO: windows_service[signalfx-agent] restarted

    - restart service windows_service[signalfx-agent]
[2019-04-16T13:37:57+00:00] INFO: Chef Run complete in 15.556592 seconds
```

The latter technically solves the issue, although it seems like something that may be patched in the future. It's not immediately urgent to do this, but I'd be interested in a better solution where the service resource can be managed properly. A way to do this would be to separate the download & unzip actions, so the process would read more as: download package -> notify service to stop -> unzip package -> notify service to start

**Comment by keitwb** [comment]
Yeah that is weird how it refers to `windows_service`...maybe `service` is just an alias for that on Windows or something.

Ok, yeah that makes sense about how to handle the service stop/start on initial install/upgrades.  I'll look into doing that.

**Comment by atoulme** [comment]
Closing this issue as inactive. Please reopen if this issue is still occurring.
