### ISSUE TITLE
helm chart crashlooping for signalfx agent. 

### ISSUE THREAD

**Issue by woojae-cohesity** [signalfx/signalfx-agent#806]
I commented out the enableBuiltInFiltering: true in the helm chart.  But not sure what that line in the config does.  

```
time="2019-05-13T20:52:38Z" level=info msg="Starting up agent version 4.6.3"
time="2019-05-13T20:52:38Z" level=info msg="Watching for config file changes"
time="2019-05-13T20:52:38Z" level=error msg="Could not unmarshal config file:

  readThreads: 5
  timeout: 40
  writeQueueLimitHigh: 500000
  writeQueueLimitLow: 400000
enableBuiltInFiltering: true
^^^^^^^
etcPath: /hostfs/etc
globalDimensions:
  kubernetes_cluster: sandbox
intervalSeconds: 20
logging:

yaml: unmarshal errors:
  line 7: field enableBuiltInFiltering not found in type config.Config
"
time="2019-05-13T20:52:38Z" level=error msg="Error loading main config" configPath="/etc/signalfx/agent.yaml" error="yaml: unmarshal errors:
  line 7: field enableBuiltInFiltering not found in type config.Config"
```

**Comment by mstumpfx** [comment]
Hi @woojae-cohesity 
This flag is a config option under development and is only in our master branch, not in any tagged releases. Commenting it out will work in your local config for now. Our master branch is a "staging for a release" type of branch, and I would not recommend pulling any configuration files from master. 
Please use our tagged release branches for this purpose.

Out of curiosity, were you cloning the repo locally to use our helm chart?
We host it ourselves now if you look at our install instructions here: https://github.com/signalfx/signalfx-agent/tree/v4.6.3/deployments/k8s/helm/signalfx-agent

**Comment by woojae-cohesity** [comment]
Thanks I was cloning from master.  Good to know I should be cloning from a release branch.
