### ISSUE TITLE
K8s: Horizontal Pod Autoscaler Metrics

### ISSUE THREAD

**Issue by daviddyball** [signalfx/signalfx-agent#945]
Hi,

It'd be great to have access to HPA metrics like:
* `hpa_current_replicas`,
* `hpa_min_replicas`
* `hpa_max_replicas`
* `hpa_desired_replicas`

These are really useful for alerting when our HPA policies are incorrectly sized. `kube-state-metrics` has similar values [here](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/horizontalpodautoscaler-metrics.md)

Cheers,
DD

**Comment by keitwb** [comment]
Absolutely, we have recently released our [metrics adapter](https://github.com/signalfx/signalfx-k8s-metrics-adapter) so it would be good to get these metrics in as well.

**Comment by keitwb** [comment]
@daviddyball This is currently being worked on and we will close this when it releases.

**Comment by keitwb** [comment]
This is about to be released today.

**Comment by jaysfx** [comment]
4.13.0 has been released.
