### ISSUE TITLE
Panic when loading config referencing non-existent environment variable

### ISSUE THREAD

**Issue by jalaziz** [signalfx/signalfx-agent#998]
When starting the agent with a config that references variables using `${}` substitution, the agent panic. In our case, the following addition to the config seems to be the culprit:
```
globalDimensions:
  env: ${ENV_NAME}
  region: ${REGION}
```

When starting the agent, it panicked with the following output:
```
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]: time="2019-09-28T01:37:52Z" level=info msg="Starting up agent version 4.11.1"
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]: time="2019-09-28T01:37:52Z" level=info msg="Watching for config file changes"
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]: panic: interface conversion: error is *errors.errorString, not *yaml.TypeError
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]: goroutine 1 [running]:
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]: github.com/signalfx/signalfx-agent/internal/core/config.loadYAML(0xc00056c000, 0x1048, 0x1300, 0x6f9, 0xc000082de0, 0xc00056c000)
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]:         /usr/src/signalfx-agent/internal/core/config/loader.go:107 +0x734
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]: github.com/signalfx/signalfx-agent/internal/core/config.LoadConfig(0x223f020, 0xc000461500, 0x1e5462d, 0x18, 0xc000123d60, 0x18, 0xc000000180)
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]:         /usr/src/signalfx-agent/internal/core/config/loader.go:42 +0x41f
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]: github.com/signalfx/signalfx-agent/internal/core.Startup(0x1e5462d, 0x18, 0xc00055fe20, 0x1)
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]:         /usr/src/signalfx-agent/internal/core/agent.go:148 +0x95
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]: main.runAgent.func1()
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]:         /usr/src/signalfx-agent/cmd/agent/main.go:191 +0xac
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]: main.runAgent(0xc00046dd10, 0xc00046a8a0, 0xc000082c60)
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]:         /usr/src/signalfx-agent/cmd/agent/main.go:194 +0xa6
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]: main.runAgentPlatformSpecific(...)
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]:         /usr/src/signalfx-agent/cmd/agent/nonwindows.go:10
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]: main.main()
Sep 28 01:37:52 ip-10-4-12-42 docker[11742]:         /usr/src/signalfx-agent/cmd/agent/main.go:277 +0x497
```

Once we made the environment variables available, the agent started up successfully.

While the agent failing to start is not unreasonable, the lack of an appropriate error message is very confusing.

**Comment by keitwb** [comment]
Thanks for reporting this @jalaziz, even after finding the solution.  The referenced PR should fix the panic and also provide clear context in the config file as to the error.  I suspect you had a variable that was getting interpreted as YAML but had some kind of parse error, as I could not reproduce it with an unset or blank envvar.  Either way, it should be easier to diagnose config errors after this PR is released.

Also, I would recommend using the following syntax to put in envvars:

```yaml
globalDimensions:
  env: {"#from": "env:ENV_NAME", raw: true}
  region: {"#from": "env:REGION", raw: true}
```

This will prevent the values from attempting to be parsed as YAML.

**Comment by jalaziz** [comment]
@keitwb Thanks for the info. You are right, it was a different block that was causing the panic:

```
- type: collectd/kafka
   serviceURL: service:jmx:rmi:///jndi/rmi://{{.Host}}:9999/jmxrmi
   clusterName: ${ENV_NAME}-${REGION}
   discoveryRule: container_name == "kafka" && port == 9092
```

Unfortunately, I don't believe  the `{"#from"}` block works for this use case unless there's an undocumented trick?

**Comment by keitwb** [comment]
Ah ok, that makes sense.  The resolved value was just `-` if both envvars were blank, which I think gets interpreted as the start of a list, resulting in a syntax error.   I just tested my PR with that particular combination and it will now give a better error message.

Yes, you are right that `#from` isn't powerful enough to combine values in an arbitrary template.  The `${}` will work fine but just remember that it pastes in the envvar values _before_ parsing it as YAML.
